package main

import (
	"fmt"
	"sort"
	"strings"
)

const header = "// Code generated by vkgen; DO NOT EDIT.\n\npackage vulkan\n"

// emitAll writes every generated file into dir.
func (b *Builder) emitAll(dir string) error {
	writers := []struct {
		file string
		fn   func(*strings.Builder)
	}{
		{"basetypes.go", b.emitBasetypes},
		{"handles.go", b.emitHandles},
		{"enums.go", b.emitEnums},
		{"bitmasks.go", b.emitBitmasks},
		{"funcpointers.go", b.emitFuncpointers},
		{"structs.go", b.emitStructs},
		{"unions.go", b.emitUnions},
		{"commands.go", b.emitCommands},
		{"loader.go", b.emitLoader},
		{"constants.go", b.emitConstants},
	}
	for _, w := range writers {
		var sb strings.Builder
		sb.WriteString(header)
		w.fn(&sb)
		if err := writeGoFile(dir+"/"+w.file, sb.String()); err != nil {
			return err
		}
	}
	return nil
}

// sortedNeededTypes returns the in-scope type names of a category, in a stable
// order (registry order then name).
func (b *Builder) neededOf(category string) []*xmlType {
	var out []*xmlType
	for i := range b.reg.Types.Type {
		t := &b.reg.Types.Type[i]
		n := typeName(t)
		if !b.needType[n] || t.Category != category {
			continue
		}
		if !apiIncludesVulkan(t.API) {
			continue // skip vulkansc-only duplicate definitions
		}
		out = append(out, t)
	}
	return out
}

// ---- basetypes ----

func (b *Builder) emitBasetypes(sb *strings.Builder) {
	sb.WriteString("\n")
	// Fixed scalar typedefs from the spec.
	fmt.Fprint(sb, `type (
	VkBool32        = uint32
	VkFlags         = uint32
	VkFlags64       = uint64
	VkDeviceSize    = uint64
	VkDeviceAddress = uint64
	VkSampleMask    = uint32
)

// VkResult is a Vulkan result code.
type VkResult int32

`)
	// Any other basetype not covered above and not platform: map via underlying.
	for _, t := range b.neededOf("basetype") {
		n := typeName(t)
		switch n {
		case "VkBool32", "VkFlags", "VkFlags64", "VkDeviceSize", "VkDeviceAddress", "VkSampleMask":
			continue
		}
		if g, ok := scalarCType(t.TypeInner); ok && g != "" {
			fmt.Fprintf(sb, "type %s = %s\n", n, g)
		}
	}
}

// ---- handles ----

func (b *Builder) emitHandles(sb *strings.Builder) {
	sb.WriteString("\n")
	var disp, nondisp []string
	for _, t := range b.neededOf("handle") {
		n := typeName(t)
		if t.Alias != "" {
			continue
		}
		if strings.Contains(t.Raw, "VK_DEFINE_NON_DISPATCHABLE_HANDLE") {
			nondisp = append(nondisp, n)
		} else {
			disp = append(disp, n)
		}
	}
	sort.Strings(disp)
	sort.Strings(nondisp)
	sb.WriteString("// Dispatchable handles are pointer-sized.\ntype (\n")
	for _, n := range disp {
		fmt.Fprintf(sb, "\t%s = uintptr\n", n)
	}
	sb.WriteString(")\n\n// Non-dispatchable handles are 64-bit on all platforms.\ntype (\n")
	for _, n := range nondisp {
		fmt.Fprintf(sb, "\t%s = uint64\n", n)
	}
	sb.WriteString(")\n\n")
	// handle aliases
	for _, t := range b.neededOf("handle") {
		if t.Alias != "" {
			fmt.Fprintf(sb, "type %s = %s\n", typeName(t), t.Alias)
		}
	}
}

// ---- enums ----

func (b *Builder) emitEnums(sb *strings.Builder) {
	sb.WriteString("\n")
	// Determine enum types: category "enum" types that are NOT bitmask FlagBits.
	var names []string
	for _, t := range b.neededOf("enum") {
		n := typeName(t)
		if _, isBits := b.bitsToFlags[n]; isBits {
			continue // bitmask bits go in bitmasks.go
		}
		if t.Alias != "" || n == "VkResult" {
			continue
		}
		names = append(names, n)
	}
	sort.Strings(names)

	// VkResult constants live here too (type defined in basetypes.go).
	b.emitEnumConstsBlock(sb, "VkResult", "VkResult")

	for _, n := range names {
		fmt.Fprintf(sb, "type %s int32\n", n)
		b.emitEnumConstsBlock(sb, n, n)
	}

	// enum aliases
	for _, t := range b.neededOf("enum") {
		if t.Alias != "" {
			if _, isBits := b.bitsToFlags[typeName(t)]; isBits {
				continue
			}
			fmt.Fprintf(sb, "type %s = %s\n", typeName(t), t.Alias)
		}
	}
}

// emitEnumConstsBlock writes the const block for an enum type, merging base
// definition values and extension-added values.
func (b *Builder) emitEnumConstsBlock(sb *strings.Builder, enumType, goType string) {
	type kv struct {
		name string
		val  int64
	}
	seen := map[string]bool{}
	var consts []kv

	// base group
	if g, ok := b.enumGroups[enumType]; ok {
		for _, c := range g.Enum {
			if c.Alias != "" || seen[c.Name] {
				continue
			}
			v, ok := b.constEnumValue(enumType, c)
			if !ok {
				continue
			}
			seen[c.Name] = true
			consts = append(consts, kv{c.Name, v})
		}
	}
	// extension-added
	for _, c := range b.enumValues[enumType] {
		if seen[c.name] {
			continue
		}
		seen[c.name] = true
		consts = append(consts, kv{c.name, c.value})
	}
	if len(consts) == 0 {
		return
	}
	sb.WriteString("const (\n")
	for _, c := range consts {
		fmt.Fprintf(sb, "\t%s %s = %d\n", c.name, goType, c.val)
	}
	sb.WriteString(")\n\n")
}

func (b *Builder) constEnumValue(enumType string, c xmlEnum) (int64, bool) {
	if c.Value != "" {
		v, err := parseIntLiteral(c.Value)
		if err != nil {
			return 0, false
		}
		return v, true
	}
	if c.BitPos != "" {
		bp := atoiSafe(c.BitPos)
		return int64(1) << uint(bp), true
	}
	return 0, false
}

// ---- bitmasks ----

func (b *Builder) emitBitmasks(sb *strings.Builder) {
	sb.WriteString("\n")
	// Flags typedefs: category "bitmask". Each gets a Go type aliasing uint32/64.
	var flagNames []string
	for _, t := range b.neededOf("bitmask") {
		if t.Alias != "" {
			continue
		}
		flagNames = append(flagNames, typeName(t))
	}
	sort.Strings(flagNames)
	for _, fn := range flagNames {
		width := b.flagWidth[fn]
		if width == "" {
			width = "uint32"
		}
		fmt.Fprintf(sb, "type %s = %s\n", fn, width)
	}
	sb.WriteString("\n")

	// FlagBits constants: emit under the Flags type when there is one, else the
	// bits name itself (define a typedef for it).
	var bitsNames []string
	for _, t := range b.neededOf("enum") {
		n := typeName(t)
		if _, isBits := b.bitsToFlags[n]; !isBits || t.Alias != "" {
			continue
		}
		bitsNames = append(bitsNames, n)
	}
	sort.Strings(bitsNames)
	for _, bn := range bitsNames {
		flagsType := b.bitsToFlags[bn]
		width := b.flagWidth[flagsType]
		if width == "" {
			width = "uint32"
		}
		// A FlagBits enum is the same width as its Flags typedef. Emit it as an
		// alias so struct members typed as the bits enum resolve.
		fmt.Fprintf(sb, "type %s = %s\n", bn, width)
		// Constants of the Flags type (already uint32/uint64).
		b.emitBitConstsBlock(sb, bn, bn, width)
	}

	// bitmask + enum aliases that are FlagBits
	for _, t := range b.neededOf("bitmask") {
		if t.Alias != "" {
			fmt.Fprintf(sb, "type %s = %s\n", typeName(t), t.Alias)
		}
	}
}

func (b *Builder) emitBitConstsBlock(sb *strings.Builder, bitsName, goType, width string) {
	type kv struct {
		name string
		u    uint64
	}
	seen := map[string]bool{}
	var consts []kv
	if g, ok := b.enumGroups[bitsName]; ok {
		for _, c := range g.Enum {
			if c.Alias != "" || seen[c.Name] {
				continue
			}
			u, ok := b.bitValue(c)
			if !ok {
				continue
			}
			seen[c.Name] = true
			consts = append(consts, kv{c.Name, u})
		}
	}
	for _, c := range b.enumValues[bitsName] {
		if seen[c.name] {
			continue
		}
		seen[c.name] = true
		consts = append(consts, kv{c.name, c.uval})
	}
	if len(consts) == 0 {
		return
	}
	sb.WriteString("const (\n")
	for _, c := range consts {
		fmt.Fprintf(sb, "\t%s %s = 0x%X\n", c.name, goType, c.u)
	}
	sb.WriteString(")\n\n")
}

func (b *Builder) bitValue(c xmlEnum) (uint64, bool) {
	if c.BitPos != "" {
		bp := atoiSafe(c.BitPos)
		return uint64(1) << uint(bp), true
	}
	if c.Value != "" {
		v, err := parseIntLiteral(c.Value)
		if err != nil {
			return 0, false
		}
		return uint64(v), true
	}
	return 0, false
}

// ---- func pointers ----

func (b *Builder) emitFuncpointers(sb *strings.Builder) {
	sb.WriteString("\n")
	var names []string
	for _, t := range b.neededOf("funcpointer") {
		names = append(names, typeName(t))
	}
	sort.Strings(names)
	for _, n := range names {
		fmt.Fprintf(sb, "type %s = uintptr\n", n)
	}
}

// ---- constants ----

func (b *Builder) emitConstants(sb *strings.Builder) {
	sb.WriteString("\n// API constants from the registry (VK_MAX_*, VK_UUID_SIZE, etc.).\nconst (\n")
	var names []string
	for n := range b.constInts {
		names = append(names, n)
	}
	sort.Strings(names)
	for _, n := range names {
		v := b.constInts[n]
		lit, ok := goConstLiteral(v)
		if !ok {
			continue
		}
		fmt.Fprintf(sb, "\t%s = %s\n", n, lit)
	}
	sb.WriteString(")\n")
}

func goConstLiteral(v string) (string, bool) {
	s := strings.TrimSpace(v)
	// strip trailing C suffixes
	for _, suf := range []string{"ULL", "LL", "U", "L", "F", "f"} {
		s = strings.TrimSuffix(s, suf)
	}
	if s == "" {
		return "", false
	}
	// floats with quotes or special forms -> skip
	if strings.ContainsAny(s, "\"") {
		return "", false
	}
	if strings.HasPrefix(s, "(~") {
		// (~0U) etc -> all-ones; represent as untyped via masking is complex; skip
		return "", false
	}
	return s, true
}
