// Code generated by vkgen; DO NOT EDIT.

package vulkan

type (
	VkBool32        = uint32
	VkFlags         = uint32
	VkFlags64       = uint64
	VkDeviceSize    = uint64
	VkDeviceAddress = uint64
	VkSampleMask    = uint32
)

// VkResult is a Vulkan result code.
type VkResult int32
