// Code generated by vkgen; DO NOT EDIT.

package vulkan

import "unsafe"

// Command function pointers. Nil until the matching Load* call binds them.
// Each variable is the exported Vk-cased name; it is bound to the real
// lowercase vk* entry point at load time.
var (
	VkAcquireDrmDisplayEXT                                          func(physicalDevice VkPhysicalDevice, drmFd int32, display VkDisplayKHR) VkResult
	VkAcquireNextImage2KHR                                          func(device VkDevice, pAcquireInfo unsafe.Pointer, pImageIndex unsafe.Pointer) VkResult
	VkAcquireNextImageKHR                                           func(device VkDevice, swapchain VkSwapchainKHR, timeout uint64, semaphore VkSemaphore, fence VkFence, pImageIndex unsafe.Pointer) VkResult
	VkAcquireProfilingLockKHR                                       func(device VkDevice, pInfo unsafe.Pointer) VkResult
	VkAllocateCommandBuffers                                        func(device VkDevice, pAllocateInfo unsafe.Pointer, pCommandBuffers unsafe.Pointer) VkResult
	VkAllocateDescriptorSets                                        func(device VkDevice, pAllocateInfo unsafe.Pointer, pDescriptorSets unsafe.Pointer) VkResult
	VkAllocateMemory                                                func(device VkDevice, pAllocateInfo unsafe.Pointer, pAllocator unsafe.Pointer, pMemory unsafe.Pointer) VkResult
	VkBeginCommandBuffer                                            func(commandBuffer VkCommandBuffer, pBeginInfo unsafe.Pointer) VkResult
	VkBindBufferMemory                                              func(device VkDevice, buffer VkBuffer, memory VkDeviceMemory, memoryOffset VkDeviceSize) VkResult
	VkBindBufferMemory2                                             func(device VkDevice, bindInfoCount uint32, pBindInfos unsafe.Pointer) VkResult
	VkBindImageMemory                                               func(device VkDevice, image VkImage, memory VkDeviceMemory, memoryOffset VkDeviceSize) VkResult
	VkBindImageMemory2                                              func(device VkDevice, bindInfoCount uint32, pBindInfos unsafe.Pointer) VkResult
	VkBindVideoSessionMemoryKHR                                     func(device VkDevice, videoSession VkVideoSessionKHR, bindSessionMemoryInfoCount uint32, pBindSessionMemoryInfos unsafe.Pointer) VkResult
	VkBuildAccelerationStructuresKHR                                func(device VkDevice, deferredOperation VkDeferredOperationKHR, infoCount uint32, pInfos unsafe.Pointer, ppBuildRangeInfos unsafe.Pointer) VkResult
	VkBuildMicromapsEXT                                             func(device VkDevice, deferredOperation VkDeferredOperationKHR, infoCount uint32, pInfos unsafe.Pointer) VkResult
	VkCmdBeginConditionalRendering2EXT                              func(commandBuffer VkCommandBuffer, pConditionalRenderingBegin unsafe.Pointer)
	VkCmdBeginConditionalRenderingEXT                               func(commandBuffer VkCommandBuffer, pConditionalRenderingBegin unsafe.Pointer)
	VkCmdBeginCustomResolveEXT                                      func(commandBuffer VkCommandBuffer, pBeginCustomResolveInfo unsafe.Pointer)
	VkCmdBeginDebugUtilsLabelEXT                                    func(commandBuffer VkCommandBuffer, pLabelInfo unsafe.Pointer)
	VkCmdBeginQuery                                                 func(commandBuffer VkCommandBuffer, queryPool VkQueryPool, query uint32, flags VkQueryControlFlags)
	VkCmdBeginQueryIndexedEXT                                       func(commandBuffer VkCommandBuffer, queryPool VkQueryPool, query uint32, flags VkQueryControlFlags, index uint32)
	VkCmdBeginRenderPass                                            func(commandBuffer VkCommandBuffer, pRenderPassBegin unsafe.Pointer, contents VkSubpassContents)
	VkCmdBeginRenderPass2                                           func(commandBuffer VkCommandBuffer, pRenderPassBegin unsafe.Pointer, pSubpassBeginInfo unsafe.Pointer)
	VkCmdBeginRendering                                             func(commandBuffer VkCommandBuffer, pRenderingInfo unsafe.Pointer)
	VkCmdBeginTransformFeedback2EXT                                 func(commandBuffer VkCommandBuffer, firstCounterRange uint32, counterRangeCount uint32, pCounterInfos unsafe.Pointer)
	VkCmdBeginTransformFeedbackEXT                                  func(commandBuffer VkCommandBuffer, firstCounterBuffer uint32, counterBufferCount uint32, pCounterBuffers unsafe.Pointer, pCounterBufferOffsets unsafe.Pointer)
	VkCmdBeginVideoCodingKHR                                        func(commandBuffer VkCommandBuffer, pBeginInfo unsafe.Pointer)
	VkCmdBindDescriptorBufferEmbeddedSamplers2EXT                   func(commandBuffer VkCommandBuffer, pBindDescriptorBufferEmbeddedSamplersInfo unsafe.Pointer)
	VkCmdBindDescriptorBufferEmbeddedSamplersEXT                    func(commandBuffer VkCommandBuffer, pipelineBindPoint VkPipelineBindPoint, layout VkPipelineLayout, set uint32)
	VkCmdBindDescriptorBuffersEXT                                   func(commandBuffer VkCommandBuffer, bufferCount uint32, pBindingInfos unsafe.Pointer)
	VkCmdBindDescriptorSets                                         func(commandBuffer VkCommandBuffer, pipelineBindPoint VkPipelineBindPoint, layout VkPipelineLayout, firstSet uint32, descriptorSetCount uint32, pDescriptorSets unsafe.Pointer, dynamicOffsetCount uint32, pDynamicOffsets unsafe.Pointer)
	VkCmdBindDescriptorSets2                                        func(commandBuffer VkCommandBuffer, pBindDescriptorSetsInfo unsafe.Pointer)
	VkCmdBindIndexBuffer                                            func(commandBuffer VkCommandBuffer, buffer VkBuffer, offset VkDeviceSize, indexType VkIndexType)
	VkCmdBindIndexBuffer2                                           func(commandBuffer VkCommandBuffer, buffer VkBuffer, offset VkDeviceSize, size VkDeviceSize, indexType VkIndexType)
	VkCmdBindIndexBuffer3KHR                                        func(commandBuffer VkCommandBuffer, pInfo unsafe.Pointer)
	VkCmdBindPipeline                                               func(commandBuffer VkCommandBuffer, pipelineBindPoint VkPipelineBindPoint, pipeline VkPipeline)
	VkCmdBindResourceHeapEXT                                        func(commandBuffer VkCommandBuffer, pBindInfo unsafe.Pointer)
	VkCmdBindSamplerHeapEXT                                         func(commandBuffer VkCommandBuffer, pBindInfo unsafe.Pointer)
	VkCmdBindShadersEXT                                             func(commandBuffer VkCommandBuffer, stageCount uint32, pStages unsafe.Pointer, pShaders unsafe.Pointer)
	VkCmdBindTransformFeedbackBuffers2EXT                           func(commandBuffer VkCommandBuffer, firstBinding uint32, bindingCount uint32, pBindingInfos unsafe.Pointer)
	VkCmdBindTransformFeedbackBuffersEXT                            func(commandBuffer VkCommandBuffer, firstBinding uint32, bindingCount uint32, pBuffers unsafe.Pointer, pOffsets unsafe.Pointer, pSizes unsafe.Pointer)
	VkCmdBindVertexBuffers                                          func(commandBuffer VkCommandBuffer, firstBinding uint32, bindingCount uint32, pBuffers unsafe.Pointer, pOffsets unsafe.Pointer)
	VkCmdBindVertexBuffers2                                         func(commandBuffer VkCommandBuffer, firstBinding uint32, bindingCount uint32, pBuffers unsafe.Pointer, pOffsets unsafe.Pointer, pSizes unsafe.Pointer, pStrides unsafe.Pointer)
	VkCmdBindVertexBuffers3KHR                                      func(commandBuffer VkCommandBuffer, firstBinding uint32, bindingCount uint32, pBindingInfos unsafe.Pointer)
	VkCmdBlitImage                                                  func(commandBuffer VkCommandBuffer, srcImage VkImage, srcImageLayout VkImageLayout, dstImage VkImage, dstImageLayout VkImageLayout, regionCount uint32, pRegions unsafe.Pointer, filter VkFilter)
	VkCmdBlitImage2                                                 func(commandBuffer VkCommandBuffer, pBlitImageInfo unsafe.Pointer)
	VkCmdBuildAccelerationStructuresIndirectKHR                     func(commandBuffer VkCommandBuffer, infoCount uint32, pInfos unsafe.Pointer, pIndirectDeviceAddresses unsafe.Pointer, pIndirectStrides unsafe.Pointer, ppMaxPrimitiveCounts unsafe.Pointer)
	VkCmdBuildAccelerationStructuresKHR                             func(commandBuffer VkCommandBuffer, infoCount uint32, pInfos unsafe.Pointer, ppBuildRangeInfos unsafe.Pointer)
	VkCmdBuildMicromapsEXT                                          func(commandBuffer VkCommandBuffer, infoCount uint32, pInfos unsafe.Pointer)
	VkCmdClearAttachments                                           func(commandBuffer VkCommandBuffer, attachmentCount uint32, pAttachments unsafe.Pointer, rectCount uint32, pRects unsafe.Pointer)
	VkCmdClearColorImage                                            func(commandBuffer VkCommandBuffer, image VkImage, imageLayout VkImageLayout, pColor unsafe.Pointer, rangeCount uint32, pRanges unsafe.Pointer)
	VkCmdClearDepthStencilImage                                     func(commandBuffer VkCommandBuffer, image VkImage, imageLayout VkImageLayout, pDepthStencil unsafe.Pointer, rangeCount uint32, pRanges unsafe.Pointer)
	VkCmdControlVideoCodingKHR                                      func(commandBuffer VkCommandBuffer, pCodingControlInfo unsafe.Pointer)
	VkCmdCopyAccelerationStructureKHR                               func(commandBuffer VkCommandBuffer, pInfo unsafe.Pointer)
	VkCmdCopyAccelerationStructureToMemoryKHR                       func(commandBuffer VkCommandBuffer, pInfo unsafe.Pointer)
	VkCmdCopyBuffer                                                 func(commandBuffer VkCommandBuffer, srcBuffer VkBuffer, dstBuffer VkBuffer, regionCount uint32, pRegions unsafe.Pointer)
	VkCmdCopyBuffer2                                                func(commandBuffer VkCommandBuffer, pCopyBufferInfo unsafe.Pointer)
	VkCmdCopyBufferToImage                                          func(commandBuffer VkCommandBuffer, srcBuffer VkBuffer, dstImage VkImage, dstImageLayout VkImageLayout, regionCount uint32, pRegions unsafe.Pointer)
	VkCmdCopyBufferToImage2                                         func(commandBuffer VkCommandBuffer, pCopyBufferToImageInfo unsafe.Pointer)
	VkCmdCopyImage                                                  func(commandBuffer VkCommandBuffer, srcImage VkImage, srcImageLayout VkImageLayout, dstImage VkImage, dstImageLayout VkImageLayout, regionCount uint32, pRegions unsafe.Pointer)
	VkCmdCopyImage2                                                 func(commandBuffer VkCommandBuffer, pCopyImageInfo unsafe.Pointer)
	VkCmdCopyImageToBuffer                                          func(commandBuffer VkCommandBuffer, srcImage VkImage, srcImageLayout VkImageLayout, dstBuffer VkBuffer, regionCount uint32, pRegions unsafe.Pointer)
	VkCmdCopyImageToBuffer2                                         func(commandBuffer VkCommandBuffer, pCopyImageToBufferInfo unsafe.Pointer)
	VkCmdCopyImageToMemoryKHR                                       func(commandBuffer VkCommandBuffer, pCopyMemoryInfo unsafe.Pointer)
	VkCmdCopyMemoryIndirectKHR                                      func(commandBuffer VkCommandBuffer, pCopyMemoryIndirectInfo unsafe.Pointer)
	VkCmdCopyMemoryKHR                                              func(commandBuffer VkCommandBuffer, pCopyMemoryInfo unsafe.Pointer)
	VkCmdCopyMemoryToAccelerationStructureKHR                       func(commandBuffer VkCommandBuffer, pInfo unsafe.Pointer)
	VkCmdCopyMemoryToImageIndirectKHR                               func(commandBuffer VkCommandBuffer, pCopyMemoryToImageIndirectInfo unsafe.Pointer)
	VkCmdCopyMemoryToImageKHR                                       func(commandBuffer VkCommandBuffer, pCopyMemoryInfo unsafe.Pointer)
	VkCmdCopyMemoryToMicromapEXT                                    func(commandBuffer VkCommandBuffer, pInfo unsafe.Pointer)
	VkCmdCopyMicromapEXT                                            func(commandBuffer VkCommandBuffer, pInfo unsafe.Pointer)
	VkCmdCopyMicromapToMemoryEXT                                    func(commandBuffer VkCommandBuffer, pInfo unsafe.Pointer)
	VkCmdCopyQueryPoolResults                                       func(commandBuffer VkCommandBuffer, queryPool VkQueryPool, firstQuery uint32, queryCount uint32, dstBuffer VkBuffer, dstOffset VkDeviceSize, stride VkDeviceSize, flags VkQueryResultFlags)
	VkCmdCopyQueryPoolResultsToMemoryKHR                            func(commandBuffer VkCommandBuffer, queryPool VkQueryPool, firstQuery uint32, queryCount uint32, pDstRange unsafe.Pointer, dstFlags VkAddressCommandFlagsKHR, queryResultFlags VkQueryResultFlags)
	VkCmdDebugMarkerBeginEXT                                        func(commandBuffer VkCommandBuffer, pMarkerInfo unsafe.Pointer)
	VkCmdDebugMarkerEndEXT                                          func(commandBuffer VkCommandBuffer)
	VkCmdDebugMarkerInsertEXT                                       func(commandBuffer VkCommandBuffer, pMarkerInfo unsafe.Pointer)
	VkCmdDecodeVideoKHR                                             func(commandBuffer VkCommandBuffer, pDecodeInfo unsafe.Pointer)
	VkCmdDecompressMemoryEXT                                        func(commandBuffer VkCommandBuffer, pDecompressMemoryInfoEXT unsafe.Pointer)
	VkCmdDecompressMemoryIndirectCountEXT                           func(commandBuffer VkCommandBuffer, decompressionMethod VkMemoryDecompressionMethodFlagsEXT, indirectCommandsAddress VkDeviceAddress, indirectCommandsCountAddress VkDeviceAddress, maxDecompressionCount uint32, stride uint32)
	VkCmdDispatch                                                   func(commandBuffer VkCommandBuffer, groupCountX uint32, groupCountY uint32, groupCountZ uint32)
	VkCmdDispatchBase                                               func(commandBuffer VkCommandBuffer, baseGroupX uint32, baseGroupY uint32, baseGroupZ uint32, groupCountX uint32, groupCountY uint32, groupCountZ uint32)
	VkCmdDispatchIndirect                                           func(commandBuffer VkCommandBuffer, buffer VkBuffer, offset VkDeviceSize)
	VkCmdDispatchIndirect2KHR                                       func(commandBuffer VkCommandBuffer, pInfo unsafe.Pointer)
	VkCmdDraw                                                       func(commandBuffer VkCommandBuffer, vertexCount uint32, instanceCount uint32, firstVertex uint32, firstInstance uint32)
	VkCmdDrawIndexed                                                func(commandBuffer VkCommandBuffer, indexCount uint32, instanceCount uint32, firstIndex uint32, vertexOffset int32, firstInstance uint32)
	VkCmdDrawIndexedIndirect                                        func(commandBuffer VkCommandBuffer, buffer VkBuffer, offset VkDeviceSize, drawCount uint32, stride uint32)
	VkCmdDrawIndexedIndirect2KHR                                    func(commandBuffer VkCommandBuffer, pInfo unsafe.Pointer)
	VkCmdDrawIndexedIndirectCount                                   func(commandBuffer VkCommandBuffer, buffer VkBuffer, offset VkDeviceSize, countBuffer VkBuffer, countBufferOffset VkDeviceSize, maxDrawCount uint32, stride uint32)
	VkCmdDrawIndexedIndirectCount2KHR                               func(commandBuffer VkCommandBuffer, pInfo unsafe.Pointer)
	VkCmdDrawIndirect                                               func(commandBuffer VkCommandBuffer, buffer VkBuffer, offset VkDeviceSize, drawCount uint32, stride uint32)
	VkCmdDrawIndirect2KHR                                           func(commandBuffer VkCommandBuffer, pInfo unsafe.Pointer)
	VkCmdDrawIndirectByteCount2EXT                                  func(commandBuffer VkCommandBuffer, instanceCount uint32, firstInstance uint32, pCounterInfo unsafe.Pointer, counterOffset uint32, vertexStride uint32)
	VkCmdDrawIndirectByteCountEXT                                   func(commandBuffer VkCommandBuffer, instanceCount uint32, firstInstance uint32, counterBuffer VkBuffer, counterBufferOffset VkDeviceSize, counterOffset uint32, vertexStride uint32)
	VkCmdDrawIndirectCount                                          func(commandBuffer VkCommandBuffer, buffer VkBuffer, offset VkDeviceSize, countBuffer VkBuffer, countBufferOffset VkDeviceSize, maxDrawCount uint32, stride uint32)
	VkCmdDrawIndirectCount2KHR                                      func(commandBuffer VkCommandBuffer, pInfo unsafe.Pointer)
	VkCmdDrawMeshTasksEXT                                           func(commandBuffer VkCommandBuffer, groupCountX uint32, groupCountY uint32, groupCountZ uint32)
	VkCmdDrawMeshTasksIndirect2EXT                                  func(commandBuffer VkCommandBuffer, pInfo unsafe.Pointer)
	VkCmdDrawMeshTasksIndirectCount2EXT                             func(commandBuffer VkCommandBuffer, pInfo unsafe.Pointer)
	VkCmdDrawMeshTasksIndirectCountEXT                              func(commandBuffer VkCommandBuffer, buffer VkBuffer, offset VkDeviceSize, countBuffer VkBuffer, countBufferOffset VkDeviceSize, maxDrawCount uint32, stride uint32)
	VkCmdDrawMeshTasksIndirectEXT                                   func(commandBuffer VkCommandBuffer, buffer VkBuffer, offset VkDeviceSize, drawCount uint32, stride uint32)
	VkCmdDrawMultiEXT                                               func(commandBuffer VkCommandBuffer, drawCount uint32, pVertexInfo unsafe.Pointer, instanceCount uint32, firstInstance uint32, stride uint32)
	VkCmdDrawMultiIndexedEXT                                        func(commandBuffer VkCommandBuffer, drawCount uint32, pIndexInfo unsafe.Pointer, instanceCount uint32, firstInstance uint32, stride uint32, pVertexOffset unsafe.Pointer)
	VkCmdEncodeVideoKHR                                             func(commandBuffer VkCommandBuffer, pEncodeInfo unsafe.Pointer)
	VkCmdEndConditionalRenderingEXT                                 func(commandBuffer VkCommandBuffer)
	VkCmdEndDebugUtilsLabelEXT                                      func(commandBuffer VkCommandBuffer)
	VkCmdEndQuery                                                   func(commandBuffer VkCommandBuffer, queryPool VkQueryPool, query uint32)
	VkCmdEndQueryIndexedEXT                                         func(commandBuffer VkCommandBuffer, queryPool VkQueryPool, query uint32, index uint32)
	VkCmdEndRenderPass                                              func(commandBuffer VkCommandBuffer)
	VkCmdEndRenderPass2                                             func(commandBuffer VkCommandBuffer, pSubpassEndInfo unsafe.Pointer)
	VkCmdEndRendering                                               func(commandBuffer VkCommandBuffer)
	VkCmdEndRendering2KHR                                           func(commandBuffer VkCommandBuffer, pRenderingEndInfo unsafe.Pointer)
	VkCmdEndTransformFeedback2EXT                                   func(commandBuffer VkCommandBuffer, firstCounterRange uint32, counterRangeCount uint32, pCounterInfos unsafe.Pointer)
	VkCmdEndTransformFeedbackEXT                                    func(commandBuffer VkCommandBuffer, firstCounterBuffer uint32, counterBufferCount uint32, pCounterBuffers unsafe.Pointer, pCounterBufferOffsets unsafe.Pointer)
	VkCmdEndVideoCodingKHR                                          func(commandBuffer VkCommandBuffer, pEndCodingInfo unsafe.Pointer)
	VkCmdExecuteCommands                                            func(commandBuffer VkCommandBuffer, commandBufferCount uint32, pCommandBuffers unsafe.Pointer)
	VkCmdExecuteGeneratedCommandsEXT                                func(commandBuffer VkCommandBuffer, isPreprocessed VkBool32, pGeneratedCommandsInfo unsafe.Pointer)
	VkCmdFillBuffer                                                 func(commandBuffer VkCommandBuffer, dstBuffer VkBuffer, dstOffset VkDeviceSize, size VkDeviceSize, data uint32)
	VkCmdFillMemoryKHR                                              func(commandBuffer VkCommandBuffer, pDstRange unsafe.Pointer, dstFlags VkAddressCommandFlagsKHR, data uint32)
	VkCmdInsertDebugUtilsLabelEXT                                   func(commandBuffer VkCommandBuffer, pLabelInfo unsafe.Pointer)
	VkCmdNextSubpass                                                func(commandBuffer VkCommandBuffer, contents VkSubpassContents)
	VkCmdNextSubpass2                                               func(commandBuffer VkCommandBuffer, pSubpassBeginInfo unsafe.Pointer, pSubpassEndInfo unsafe.Pointer)
	VkCmdPipelineBarrier                                            func(commandBuffer VkCommandBuffer, srcStageMask VkPipelineStageFlags, dstStageMask VkPipelineStageFlags, dependencyFlags VkDependencyFlags, memoryBarrierCount uint32, pMemoryBarriers unsafe.Pointer, bufferMemoryBarrierCount uint32, pBufferMemoryBarriers unsafe.Pointer, imageMemoryBarrierCount uint32, pImageMemoryBarriers unsafe.Pointer)
	VkCmdPipelineBarrier2                                           func(commandBuffer VkCommandBuffer, pDependencyInfo unsafe.Pointer)
	VkCmdPreprocessGeneratedCommandsEXT                             func(commandBuffer VkCommandBuffer, pGeneratedCommandsInfo unsafe.Pointer, stateCommandBuffer VkCommandBuffer)
	VkCmdPushConstants                                              func(commandBuffer VkCommandBuffer, layout VkPipelineLayout, stageFlags VkShaderStageFlags, offset uint32, size uint32, pValues unsafe.Pointer)
	VkCmdPushConstants2                                             func(commandBuffer VkCommandBuffer, pPushConstantsInfo unsafe.Pointer)
	VkCmdPushDataEXT                                                func(commandBuffer VkCommandBuffer, pPushDataInfo unsafe.Pointer)
	VkCmdPushDescriptorSet                                          func(commandBuffer VkCommandBuffer, pipelineBindPoint VkPipelineBindPoint, layout VkPipelineLayout, set uint32, descriptorWriteCount uint32, pDescriptorWrites unsafe.Pointer)
	VkCmdPushDescriptorSet2                                         func(commandBuffer VkCommandBuffer, pPushDescriptorSetInfo unsafe.Pointer)
	VkCmdPushDescriptorSetWithTemplate                              func(commandBuffer VkCommandBuffer, descriptorUpdateTemplate VkDescriptorUpdateTemplate, layout VkPipelineLayout, set uint32, pData unsafe.Pointer)
	VkCmdPushDescriptorSetWithTemplate2                             func(commandBuffer VkCommandBuffer, pPushDescriptorSetWithTemplateInfo unsafe.Pointer)
	VkCmdResetEvent                                                 func(commandBuffer VkCommandBuffer, event VkEvent, stageMask VkPipelineStageFlags)
	VkCmdResetEvent2                                                func(commandBuffer VkCommandBuffer, event VkEvent, stageMask VkPipelineStageFlags2)
	VkCmdResetQueryPool                                             func(commandBuffer VkCommandBuffer, queryPool VkQueryPool, firstQuery uint32, queryCount uint32)
	VkCmdResolveImage                                               func(commandBuffer VkCommandBuffer, srcImage VkImage, srcImageLayout VkImageLayout, dstImage VkImage, dstImageLayout VkImageLayout, regionCount uint32, pRegions unsafe.Pointer)
	VkCmdResolveImage2                                              func(commandBuffer VkCommandBuffer, pResolveImageInfo unsafe.Pointer)
	VkCmdSetAlphaToCoverageEnableEXT                                func(commandBuffer VkCommandBuffer, alphaToCoverageEnable VkBool32)
	VkCmdSetAlphaToOneEnableEXT                                     func(commandBuffer VkCommandBuffer, alphaToOneEnable VkBool32)
	VkCmdSetAttachmentFeedbackLoopEnableEXT                         func(commandBuffer VkCommandBuffer, aspectMask VkImageAspectFlags)
	VkCmdSetBlendConstants                                          func(commandBuffer VkCommandBuffer, blendConstants unsafe.Pointer)
	VkCmdSetColorBlendAdvancedEXT                                   func(commandBuffer VkCommandBuffer, firstAttachment uint32, attachmentCount uint32, pColorBlendAdvanced unsafe.Pointer)
	VkCmdSetColorBlendEnableEXT                                     func(commandBuffer VkCommandBuffer, firstAttachment uint32, attachmentCount uint32, pColorBlendEnables unsafe.Pointer)
	VkCmdSetColorBlendEquationEXT                                   func(commandBuffer VkCommandBuffer, firstAttachment uint32, attachmentCount uint32, pColorBlendEquations unsafe.Pointer)
	VkCmdSetColorWriteEnableEXT                                     func(commandBuffer VkCommandBuffer, attachmentCount uint32, pColorWriteEnables unsafe.Pointer)
	VkCmdSetColorWriteMaskEXT                                       func(commandBuffer VkCommandBuffer, firstAttachment uint32, attachmentCount uint32, pColorWriteMasks unsafe.Pointer)
	VkCmdSetConservativeRasterizationModeEXT                        func(commandBuffer VkCommandBuffer, conservativeRasterizationMode VkConservativeRasterizationModeEXT)
	VkCmdSetCoverageModulationModeNV                                func(commandBuffer VkCommandBuffer, coverageModulationMode VkCoverageModulationModeNV)
	VkCmdSetCoverageModulationTableEnableNV                         func(commandBuffer VkCommandBuffer, coverageModulationTableEnable VkBool32)
	VkCmdSetCoverageModulationTableNV                               func(commandBuffer VkCommandBuffer, coverageModulationTableCount uint32, pCoverageModulationTable unsafe.Pointer)
	VkCmdSetCoverageReductionModeNV                                 func(commandBuffer VkCommandBuffer, coverageReductionMode VkCoverageReductionModeNV)
	VkCmdSetCoverageToColorEnableNV                                 func(commandBuffer VkCommandBuffer, coverageToColorEnable VkBool32)
	VkCmdSetCoverageToColorLocationNV                               func(commandBuffer VkCommandBuffer, coverageToColorLocation uint32)
	VkCmdSetCullMode                                                func(commandBuffer VkCommandBuffer, cullMode VkCullModeFlags)
	VkCmdSetDepthBias                                               func(commandBuffer VkCommandBuffer, depthBiasConstantFactor float32, depthBiasClamp float32, depthBiasSlopeFactor float32)
	VkCmdSetDepthBias2EXT                                           func(commandBuffer VkCommandBuffer, pDepthBiasInfo unsafe.Pointer)
	VkCmdSetDepthBiasEnable                                         func(commandBuffer VkCommandBuffer, depthBiasEnable VkBool32)
	VkCmdSetDepthBounds                                             func(commandBuffer VkCommandBuffer, minDepthBounds float32, maxDepthBounds float32)
	VkCmdSetDepthBoundsTestEnable                                   func(commandBuffer VkCommandBuffer, depthBoundsTestEnable VkBool32)
	VkCmdSetDepthClampEnableEXT                                     func(commandBuffer VkCommandBuffer, depthClampEnable VkBool32)
	VkCmdSetDepthClampRangeEXT                                      func(commandBuffer VkCommandBuffer, depthClampMode VkDepthClampModeEXT, pDepthClampRange unsafe.Pointer)
	VkCmdSetDepthClipEnableEXT                                      func(commandBuffer VkCommandBuffer, depthClipEnable VkBool32)
	VkCmdSetDepthClipNegativeOneToOneEXT                            func(commandBuffer VkCommandBuffer, negativeOneToOne VkBool32)
	VkCmdSetDepthCompareOp                                          func(commandBuffer VkCommandBuffer, depthCompareOp VkCompareOp)
	VkCmdSetDepthTestEnable                                         func(commandBuffer VkCommandBuffer, depthTestEnable VkBool32)
	VkCmdSetDepthWriteEnable                                        func(commandBuffer VkCommandBuffer, depthWriteEnable VkBool32)
	VkCmdSetDescriptorBufferOffsets2EXT                             func(commandBuffer VkCommandBuffer, pSetDescriptorBufferOffsetsInfo unsafe.Pointer)
	VkCmdSetDescriptorBufferOffsetsEXT                              func(commandBuffer VkCommandBuffer, pipelineBindPoint VkPipelineBindPoint, layout VkPipelineLayout, firstSet uint32, setCount uint32, pBufferIndices unsafe.Pointer, pOffsets unsafe.Pointer)
	VkCmdSetDeviceMask                                              func(commandBuffer VkCommandBuffer, deviceMask uint32)
	VkCmdSetDiscardRectangleEXT                                     func(commandBuffer VkCommandBuffer, firstDiscardRectangle uint32, discardRectangleCount uint32, pDiscardRectangles unsafe.Pointer)
	VkCmdSetDiscardRectangleEnableEXT                               func(commandBuffer VkCommandBuffer, discardRectangleEnable VkBool32)
	VkCmdSetDiscardRectangleModeEXT                                 func(commandBuffer VkCommandBuffer, discardRectangleMode VkDiscardRectangleModeEXT)
	VkCmdSetEvent                                                   func(commandBuffer VkCommandBuffer, event VkEvent, stageMask VkPipelineStageFlags)
	VkCmdSetEvent2                                                  func(commandBuffer VkCommandBuffer, event VkEvent, pDependencyInfo unsafe.Pointer)
	VkCmdSetExtraPrimitiveOverestimationSizeEXT                     func(commandBuffer VkCommandBuffer, extraPrimitiveOverestimationSize float32)
	VkCmdSetFragmentShadingRateKHR                                  func(commandBuffer VkCommandBuffer, pFragmentSize unsafe.Pointer, combinerOps unsafe.Pointer)
	VkCmdSetFrontFace                                               func(commandBuffer VkCommandBuffer, frontFace VkFrontFace)
	VkCmdSetLineRasterizationModeEXT                                func(commandBuffer VkCommandBuffer, lineRasterizationMode VkLineRasterizationModeEXT)
	VkCmdSetLineStipple                                             func(commandBuffer VkCommandBuffer, lineStippleFactor uint32, lineStipplePattern uint16)
	VkCmdSetLineStippleEnableEXT                                    func(commandBuffer VkCommandBuffer, stippledLineEnable VkBool32)
	VkCmdSetLineWidth                                               func(commandBuffer VkCommandBuffer, lineWidth float32)
	VkCmdSetLogicOpEXT                                              func(commandBuffer VkCommandBuffer, logicOp VkLogicOp)
	VkCmdSetLogicOpEnableEXT                                        func(commandBuffer VkCommandBuffer, logicOpEnable VkBool32)
	VkCmdSetPatchControlPointsEXT                                   func(commandBuffer VkCommandBuffer, patchControlPoints uint32)
	VkCmdSetPolygonModeEXT                                          func(commandBuffer VkCommandBuffer, polygonMode VkPolygonMode)
	VkCmdSetPrimitiveRestartEnable                                  func(commandBuffer VkCommandBuffer, primitiveRestartEnable VkBool32)
	VkCmdSetPrimitiveRestartIndexEXT                                func(commandBuffer VkCommandBuffer, primitiveRestartIndex uint32)
	VkCmdSetPrimitiveTopology                                       func(commandBuffer VkCommandBuffer, primitiveTopology VkPrimitiveTopology)
	VkCmdSetProvokingVertexModeEXT                                  func(commandBuffer VkCommandBuffer, provokingVertexMode VkProvokingVertexModeEXT)
	VkCmdSetRasterizationSamplesEXT                                 func(commandBuffer VkCommandBuffer, rasterizationSamples VkSampleCountFlagBits)
	VkCmdSetRasterizationStreamEXT                                  func(commandBuffer VkCommandBuffer, rasterizationStream uint32)
	VkCmdSetRasterizerDiscardEnable                                 func(commandBuffer VkCommandBuffer, rasterizerDiscardEnable VkBool32)
	VkCmdSetRayTracingPipelineStackSizeKHR                          func(commandBuffer VkCommandBuffer, pipelineStackSize uint32)
	VkCmdSetRenderingAttachmentLocations                            func(commandBuffer VkCommandBuffer, pLocationInfo unsafe.Pointer)
	VkCmdSetRenderingInputAttachmentIndices                         func(commandBuffer VkCommandBuffer, pInputAttachmentIndexInfo unsafe.Pointer)
	VkCmdSetRepresentativeFragmentTestEnableNV                      func(commandBuffer VkCommandBuffer, representativeFragmentTestEnable VkBool32)
	VkCmdSetSampleLocationsEXT                                      func(commandBuffer VkCommandBuffer, pSampleLocationsInfo unsafe.Pointer)
	VkCmdSetSampleLocationsEnableEXT                                func(commandBuffer VkCommandBuffer, sampleLocationsEnable VkBool32)
	VkCmdSetSampleMaskEXT                                           func(commandBuffer VkCommandBuffer, samples VkSampleCountFlagBits, pSampleMask unsafe.Pointer)
	VkCmdSetScissor                                                 func(commandBuffer VkCommandBuffer, firstScissor uint32, scissorCount uint32, pScissors unsafe.Pointer)
	VkCmdSetScissorWithCount                                        func(commandBuffer VkCommandBuffer, scissorCount uint32, pScissors unsafe.Pointer)
	VkCmdSetShadingRateImageEnableNV                                func(commandBuffer VkCommandBuffer, shadingRateImageEnable VkBool32)
	VkCmdSetStencilCompareMask                                      func(commandBuffer VkCommandBuffer, faceMask VkStencilFaceFlags, compareMask uint32)
	VkCmdSetStencilOp                                               func(commandBuffer VkCommandBuffer, faceMask VkStencilFaceFlags, failOp VkStencilOp, passOp VkStencilOp, depthFailOp VkStencilOp, compareOp VkCompareOp)
	VkCmdSetStencilReference                                        func(commandBuffer VkCommandBuffer, faceMask VkStencilFaceFlags, reference uint32)
	VkCmdSetStencilTestEnable                                       func(commandBuffer VkCommandBuffer, stencilTestEnable VkBool32)
	VkCmdSetStencilWriteMask                                        func(commandBuffer VkCommandBuffer, faceMask VkStencilFaceFlags, writeMask uint32)
	VkCmdSetTessellationDomainOriginEXT                             func(commandBuffer VkCommandBuffer, domainOrigin VkTessellationDomainOrigin)
	VkCmdSetVertexInputEXT                                          func(commandBuffer VkCommandBuffer, vertexBindingDescriptionCount uint32, pVertexBindingDescriptions unsafe.Pointer, vertexAttributeDescriptionCount uint32, pVertexAttributeDescriptions unsafe.Pointer)
	VkCmdSetViewport                                                func(commandBuffer VkCommandBuffer, firstViewport uint32, viewportCount uint32, pViewports unsafe.Pointer)
	VkCmdSetViewportSwizzleNV                                       func(commandBuffer VkCommandBuffer, firstViewport uint32, viewportCount uint32, pViewportSwizzles unsafe.Pointer)
	VkCmdSetViewportWScalingEnableNV                                func(commandBuffer VkCommandBuffer, viewportWScalingEnable VkBool32)
	VkCmdSetViewportWithCount                                       func(commandBuffer VkCommandBuffer, viewportCount uint32, pViewports unsafe.Pointer)
	VkCmdTraceRaysIndirect2KHR                                      func(commandBuffer VkCommandBuffer, indirectDeviceAddress VkDeviceAddress)
	VkCmdTraceRaysIndirectKHR                                       func(commandBuffer VkCommandBuffer, pRaygenShaderBindingTable unsafe.Pointer, pMissShaderBindingTable unsafe.Pointer, pHitShaderBindingTable unsafe.Pointer, pCallableShaderBindingTable unsafe.Pointer, indirectDeviceAddress VkDeviceAddress)
	VkCmdTraceRaysKHR                                               func(commandBuffer VkCommandBuffer, pRaygenShaderBindingTable unsafe.Pointer, pMissShaderBindingTable unsafe.Pointer, pHitShaderBindingTable unsafe.Pointer, pCallableShaderBindingTable unsafe.Pointer, width uint32, height uint32, depth uint32)
	VkCmdUpdateBuffer                                               func(commandBuffer VkCommandBuffer, dstBuffer VkBuffer, dstOffset VkDeviceSize, dataSize VkDeviceSize, pData unsafe.Pointer)
	VkCmdUpdateMemoryKHR                                            func(commandBuffer VkCommandBuffer, pDstRange unsafe.Pointer, dstFlags VkAddressCommandFlagsKHR, dataSize VkDeviceSize, pData unsafe.Pointer)
	VkCmdWaitEvents                                                 func(commandBuffer VkCommandBuffer, eventCount uint32, pEvents unsafe.Pointer, srcStageMask VkPipelineStageFlags, dstStageMask VkPipelineStageFlags, memoryBarrierCount uint32, pMemoryBarriers unsafe.Pointer, bufferMemoryBarrierCount uint32, pBufferMemoryBarriers unsafe.Pointer, imageMemoryBarrierCount uint32, pImageMemoryBarriers unsafe.Pointer)
	VkCmdWaitEvents2                                                func(commandBuffer VkCommandBuffer, eventCount uint32, pEvents unsafe.Pointer, pDependencyInfos unsafe.Pointer)
	VkCmdWriteAccelerationStructuresPropertiesKHR                   func(commandBuffer VkCommandBuffer, accelerationStructureCount uint32, pAccelerationStructures unsafe.Pointer, queryType VkQueryType, queryPool VkQueryPool, firstQuery uint32)
	VkCmdWriteMarkerToMemoryAMD                                     func(commandBuffer VkCommandBuffer, pInfo unsafe.Pointer)
	VkCmdWriteMicromapsPropertiesEXT                                func(commandBuffer VkCommandBuffer, micromapCount uint32, pMicromaps unsafe.Pointer, queryType VkQueryType, queryPool VkQueryPool, firstQuery uint32)
	VkCmdWriteTimestamp                                             func(commandBuffer VkCommandBuffer, pipelineStage VkPipelineStageFlagBits, queryPool VkQueryPool, query uint32)
	VkCmdWriteTimestamp2                                            func(commandBuffer VkCommandBuffer, stage VkPipelineStageFlags2, queryPool VkQueryPool, query uint32)
	VkCopyAccelerationStructureKHR                                  func(device VkDevice, deferredOperation VkDeferredOperationKHR, pInfo unsafe.Pointer) VkResult
	VkCopyAccelerationStructureToMemoryKHR                          func(device VkDevice, deferredOperation VkDeferredOperationKHR, pInfo unsafe.Pointer) VkResult
	VkCopyImageToImage                                              func(device VkDevice, pCopyImageToImageInfo unsafe.Pointer) VkResult
	VkCopyImageToMemory                                             func(device VkDevice, pCopyImageToMemoryInfo unsafe.Pointer) VkResult
	VkCopyMemoryToAccelerationStructureKHR                          func(device VkDevice, deferredOperation VkDeferredOperationKHR, pInfo unsafe.Pointer) VkResult
	VkCopyMemoryToImage                                             func(device VkDevice, pCopyMemoryToImageInfo unsafe.Pointer) VkResult
	VkCopyMemoryToMicromapEXT                                       func(device VkDevice, deferredOperation VkDeferredOperationKHR, pInfo unsafe.Pointer) VkResult
	VkCopyMicromapEXT                                               func(device VkDevice, deferredOperation VkDeferredOperationKHR, pInfo unsafe.Pointer) VkResult
	VkCopyMicromapToMemoryEXT                                       func(device VkDevice, deferredOperation VkDeferredOperationKHR, pInfo unsafe.Pointer) VkResult
	VkCreateAccelerationStructure2KHR                               func(device VkDevice, pCreateInfo unsafe.Pointer, pAllocator unsafe.Pointer, pAccelerationStructure unsafe.Pointer) VkResult
	VkCreateAccelerationStructureKHR                                func(device VkDevice, pCreateInfo unsafe.Pointer, pAllocator unsafe.Pointer, pAccelerationStructure unsafe.Pointer) VkResult
	VkCreateBuffer                                                  func(device VkDevice, pCreateInfo unsafe.Pointer, pAllocator unsafe.Pointer, pBuffer unsafe.Pointer) VkResult
	VkCreateBufferView                                              func(device VkDevice, pCreateInfo unsafe.Pointer, pAllocator unsafe.Pointer, pView unsafe.Pointer) VkResult
	VkCreateCommandPool                                             func(device VkDevice, pCreateInfo unsafe.Pointer, pAllocator unsafe.Pointer, pCommandPool unsafe.Pointer) VkResult
	VkCreateComputePipelines                                        func(device VkDevice, pipelineCache VkPipelineCache, createInfoCount uint32, pCreateInfos unsafe.Pointer, pAllocator unsafe.Pointer, pPipelines unsafe.Pointer) VkResult
	VkCreateDebugReportCallbackEXT                                  func(instance VkInstance, pCreateInfo unsafe.Pointer, pAllocator unsafe.Pointer, pCallback unsafe.Pointer) VkResult
	VkCreateDebugUtilsMessengerEXT                                  func(instance VkInstance, pCreateInfo unsafe.Pointer, pAllocator unsafe.Pointer, pMessenger unsafe.Pointer) VkResult
	VkCreateDeferredOperationKHR                                    func(device VkDevice, pAllocator unsafe.Pointer, pDeferredOperation unsafe.Pointer) VkResult
	VkCreateDescriptorPool                                          func(device VkDevice, pCreateInfo unsafe.Pointer, pAllocator unsafe.Pointer, pDescriptorPool unsafe.Pointer) VkResult
	VkCreateDescriptorSetLayout                                     func(device VkDevice, pCreateInfo unsafe.Pointer, pAllocator unsafe.Pointer, pSetLayout unsafe.Pointer) VkResult
	VkCreateDescriptorUpdateTemplate                                func(device VkDevice, pCreateInfo unsafe.Pointer, pAllocator unsafe.Pointer, pDescriptorUpdateTemplate unsafe.Pointer) VkResult
	VkCreateDevice                                                  func(physicalDevice VkPhysicalDevice, pCreateInfo unsafe.Pointer, pAllocator unsafe.Pointer, pDevice unsafe.Pointer) VkResult
	VkCreateDisplayModeKHR                                          func(physicalDevice VkPhysicalDevice, display VkDisplayKHR, pCreateInfo unsafe.Pointer, pAllocator unsafe.Pointer, pMode unsafe.Pointer) VkResult
	VkCreateDisplayPlaneSurfaceKHR                                  func(instance VkInstance, pCreateInfo unsafe.Pointer, pAllocator unsafe.Pointer, pSurface unsafe.Pointer) VkResult
	VkCreateEvent                                                   func(device VkDevice, pCreateInfo unsafe.Pointer, pAllocator unsafe.Pointer, pEvent unsafe.Pointer) VkResult
	VkCreateFence                                                   func(device VkDevice, pCreateInfo unsafe.Pointer, pAllocator unsafe.Pointer, pFence unsafe.Pointer) VkResult
	VkCreateFramebuffer                                             func(device VkDevice, pCreateInfo unsafe.Pointer, pAllocator unsafe.Pointer, pFramebuffer unsafe.Pointer) VkResult
	VkCreateGraphicsPipelines                                       func(device VkDevice, pipelineCache VkPipelineCache, createInfoCount uint32, pCreateInfos unsafe.Pointer, pAllocator unsafe.Pointer, pPipelines unsafe.Pointer) VkResult
	VkCreateHeadlessSurfaceEXT                                      func(instance VkInstance, pCreateInfo unsafe.Pointer, pAllocator unsafe.Pointer, pSurface unsafe.Pointer) VkResult
	VkCreateImage                                                   func(device VkDevice, pCreateInfo unsafe.Pointer, pAllocator unsafe.Pointer, pImage unsafe.Pointer) VkResult
	VkCreateImageView                                               func(device VkDevice, pCreateInfo unsafe.Pointer, pAllocator unsafe.Pointer, pView unsafe.Pointer) VkResult
	VkCreateIndirectCommandsLayoutEXT                               func(device VkDevice, pCreateInfo unsafe.Pointer, pAllocator unsafe.Pointer, pIndirectCommandsLayout unsafe.Pointer) VkResult
	VkCreateIndirectExecutionSetEXT                                 func(device VkDevice, pCreateInfo unsafe.Pointer, pAllocator unsafe.Pointer, pIndirectExecutionSet unsafe.Pointer) VkResult
	VkCreateInstance                                                func(pCreateInfo unsafe.Pointer, pAllocator unsafe.Pointer, pInstance unsafe.Pointer) VkResult
	VkCreateMicromapEXT                                             func(device VkDevice, pCreateInfo unsafe.Pointer, pAllocator unsafe.Pointer, pMicromap unsafe.Pointer) VkResult
	VkCreatePipelineBinariesKHR                                     func(device VkDevice, pCreateInfo unsafe.Pointer, pAllocator unsafe.Pointer, pBinaries unsafe.Pointer) VkResult
	VkCreatePipelineCache                                           func(device VkDevice, pCreateInfo unsafe.Pointer, pAllocator unsafe.Pointer, pPipelineCache unsafe.Pointer) VkResult
	VkCreatePipelineLayout                                          func(device VkDevice, pCreateInfo unsafe.Pointer, pAllocator unsafe.Pointer, pPipelineLayout unsafe.Pointer) VkResult
	VkCreatePrivateDataSlot                                         func(device VkDevice, pCreateInfo unsafe.Pointer, pAllocator unsafe.Pointer, pPrivateDataSlot unsafe.Pointer) VkResult
	VkCreateQueryPool                                               func(device VkDevice, pCreateInfo unsafe.Pointer, pAllocator unsafe.Pointer, pQueryPool unsafe.Pointer) VkResult
	VkCreateRayTracingPipelinesKHR                                  func(device VkDevice, deferredOperation VkDeferredOperationKHR, pipelineCache VkPipelineCache, createInfoCount uint32, pCreateInfos unsafe.Pointer, pAllocator unsafe.Pointer, pPipelines unsafe.Pointer) VkResult
	VkCreateRenderPass                                              func(device VkDevice, pCreateInfo unsafe.Pointer, pAllocator unsafe.Pointer, pRenderPass unsafe.Pointer) VkResult
	VkCreateRenderPass2                                             func(device VkDevice, pCreateInfo unsafe.Pointer, pAllocator unsafe.Pointer, pRenderPass unsafe.Pointer) VkResult
	VkCreateSampler                                                 func(device VkDevice, pCreateInfo unsafe.Pointer, pAllocator unsafe.Pointer, pSampler unsafe.Pointer) VkResult
	VkCreateSamplerYcbcrConversion                                  func(device VkDevice, pCreateInfo unsafe.Pointer, pAllocator unsafe.Pointer, pYcbcrConversion unsafe.Pointer) VkResult
	VkCreateSemaphore                                               func(device VkDevice, pCreateInfo unsafe.Pointer, pAllocator unsafe.Pointer, pSemaphore unsafe.Pointer) VkResult
	VkCreateShaderModule                                            func(device VkDevice, pCreateInfo unsafe.Pointer, pAllocator unsafe.Pointer, pShaderModule unsafe.Pointer) VkResult
	VkCreateShadersEXT                                              func(device VkDevice, createInfoCount uint32, pCreateInfos unsafe.Pointer, pAllocator unsafe.Pointer, pShaders unsafe.Pointer) VkResult
	VkCreateSharedSwapchainsKHR                                     func(device VkDevice, swapchainCount uint32, pCreateInfos unsafe.Pointer, pAllocator unsafe.Pointer, pSwapchains unsafe.Pointer) VkResult
	VkCreateSwapchainKHR                                            func(device VkDevice, pCreateInfo unsafe.Pointer, pAllocator unsafe.Pointer, pSwapchain unsafe.Pointer) VkResult
	VkCreateValidationCacheEXT                                      func(device VkDevice, pCreateInfo unsafe.Pointer, pAllocator unsafe.Pointer, pValidationCache unsafe.Pointer) VkResult
	VkCreateVideoSessionKHR                                         func(device VkDevice, pCreateInfo unsafe.Pointer, pAllocator unsafe.Pointer, pVideoSession unsafe.Pointer) VkResult
	VkCreateVideoSessionParametersKHR                               func(device VkDevice, pCreateInfo unsafe.Pointer, pAllocator unsafe.Pointer, pVideoSessionParameters unsafe.Pointer) VkResult
	VkDebugMarkerSetObjectNameEXT                                   func(device VkDevice, pNameInfo unsafe.Pointer) VkResult
	VkDebugMarkerSetObjectTagEXT                                    func(device VkDevice, pTagInfo unsafe.Pointer) VkResult
	VkDebugReportMessageEXT                                         func(instance VkInstance, flags VkDebugReportFlagsEXT, objectType VkDebugReportObjectTypeEXT, object uint64, location uintptr, messageCode int32, pLayerPrefix unsafe.Pointer, pMessage unsafe.Pointer)
	VkDeferredOperationJoinKHR                                      func(device VkDevice, operation VkDeferredOperationKHR) VkResult
	VkDestroyAccelerationStructureKHR                               func(device VkDevice, accelerationStructure VkAccelerationStructureKHR, pAllocator unsafe.Pointer)
	VkDestroyBuffer                                                 func(device VkDevice, buffer VkBuffer, pAllocator unsafe.Pointer)
	VkDestroyBufferView                                             func(device VkDevice, bufferView VkBufferView, pAllocator unsafe.Pointer)
	VkDestroyCommandPool                                            func(device VkDevice, commandPool VkCommandPool, pAllocator unsafe.Pointer)
	VkDestroyDebugReportCallbackEXT                                 func(instance VkInstance, callback VkDebugReportCallbackEXT, pAllocator unsafe.Pointer)
	VkDestroyDebugUtilsMessengerEXT                                 func(instance VkInstance, messenger VkDebugUtilsMessengerEXT, pAllocator unsafe.Pointer)
	VkDestroyDeferredOperationKHR                                   func(device VkDevice, operation VkDeferredOperationKHR, pAllocator unsafe.Pointer)
	VkDestroyDescriptorPool                                         func(device VkDevice, descriptorPool VkDescriptorPool, pAllocator unsafe.Pointer)
	VkDestroyDescriptorSetLayout                                    func(device VkDevice, descriptorSetLayout VkDescriptorSetLayout, pAllocator unsafe.Pointer)
	VkDestroyDescriptorUpdateTemplate                               func(device VkDevice, descriptorUpdateTemplate VkDescriptorUpdateTemplate, pAllocator unsafe.Pointer)
	VkDestroyDevice                                                 func(device VkDevice, pAllocator unsafe.Pointer)
	VkDestroyEvent                                                  func(device VkDevice, event VkEvent, pAllocator unsafe.Pointer)
	VkDestroyFence                                                  func(device VkDevice, fence VkFence, pAllocator unsafe.Pointer)
	VkDestroyFramebuffer                                            func(device VkDevice, framebuffer VkFramebuffer, pAllocator unsafe.Pointer)
	VkDestroyImage                                                  func(device VkDevice, image VkImage, pAllocator unsafe.Pointer)
	VkDestroyImageView                                              func(device VkDevice, imageView VkImageView, pAllocator unsafe.Pointer)
	VkDestroyIndirectCommandsLayoutEXT                              func(device VkDevice, indirectCommandsLayout VkIndirectCommandsLayoutEXT, pAllocator unsafe.Pointer)
	VkDestroyIndirectExecutionSetEXT                                func(device VkDevice, indirectExecutionSet VkIndirectExecutionSetEXT, pAllocator unsafe.Pointer)
	VkDestroyInstance                                               func(instance VkInstance, pAllocator unsafe.Pointer)
	VkDestroyMicromapEXT                                            func(device VkDevice, micromap VkMicromapEXT, pAllocator unsafe.Pointer)
	VkDestroyPipeline                                               func(device VkDevice, pipeline VkPipeline, pAllocator unsafe.Pointer)
	VkDestroyPipelineBinaryKHR                                      func(device VkDevice, pipelineBinary VkPipelineBinaryKHR, pAllocator unsafe.Pointer)
	VkDestroyPipelineCache                                          func(device VkDevice, pipelineCache VkPipelineCache, pAllocator unsafe.Pointer)
	VkDestroyPipelineLayout                                         func(device VkDevice, pipelineLayout VkPipelineLayout, pAllocator unsafe.Pointer)
	VkDestroyPrivateDataSlot                                        func(device VkDevice, privateDataSlot VkPrivateDataSlot, pAllocator unsafe.Pointer)
	VkDestroyQueryPool                                              func(device VkDevice, queryPool VkQueryPool, pAllocator unsafe.Pointer)
	VkDestroyRenderPass                                             func(device VkDevice, renderPass VkRenderPass, pAllocator unsafe.Pointer)
	VkDestroySampler                                                func(device VkDevice, sampler VkSampler, pAllocator unsafe.Pointer)
	VkDestroySamplerYcbcrConversion                                 func(device VkDevice, ycbcrConversion VkSamplerYcbcrConversion, pAllocator unsafe.Pointer)
	VkDestroySemaphore                                              func(device VkDevice, semaphore VkSemaphore, pAllocator unsafe.Pointer)
	VkDestroyShaderEXT                                              func(device VkDevice, shader VkShaderEXT, pAllocator unsafe.Pointer)
	VkDestroyShaderModule                                           func(device VkDevice, shaderModule VkShaderModule, pAllocator unsafe.Pointer)
	VkDestroySurfaceKHR                                             func(instance VkInstance, surface VkSurfaceKHR, pAllocator unsafe.Pointer)
	VkDestroySwapchainKHR                                           func(device VkDevice, swapchain VkSwapchainKHR, pAllocator unsafe.Pointer)
	VkDestroyValidationCacheEXT                                     func(device VkDevice, validationCache VkValidationCacheEXT, pAllocator unsafe.Pointer)
	VkDestroyVideoSessionKHR                                        func(device VkDevice, videoSession VkVideoSessionKHR, pAllocator unsafe.Pointer)
	VkDestroyVideoSessionParametersKHR                              func(device VkDevice, videoSessionParameters VkVideoSessionParametersKHR, pAllocator unsafe.Pointer)
	VkDeviceWaitIdle                                                func(device VkDevice) VkResult
	VkDisplayPowerControlEXT                                        func(device VkDevice, display VkDisplayKHR, pDisplayPowerInfo unsafe.Pointer) VkResult
	VkEndCommandBuffer                                              func(commandBuffer VkCommandBuffer) VkResult
	VkEnumerateDeviceExtensionProperties                            func(physicalDevice VkPhysicalDevice, pLayerName unsafe.Pointer, pPropertyCount unsafe.Pointer, pProperties unsafe.Pointer) VkResult
	VkEnumerateDeviceLayerProperties                                func(physicalDevice VkPhysicalDevice, pPropertyCount unsafe.Pointer, pProperties unsafe.Pointer) VkResult
	VkEnumerateInstanceExtensionProperties                          func(pLayerName unsafe.Pointer, pPropertyCount unsafe.Pointer, pProperties unsafe.Pointer) VkResult
	VkEnumerateInstanceLayerProperties                              func(pPropertyCount unsafe.Pointer, pProperties unsafe.Pointer) VkResult
	VkEnumerateInstanceVersion                                      func(pApiVersion unsafe.Pointer) VkResult
	VkEnumeratePhysicalDeviceGroups                                 func(instance VkInstance, pPhysicalDeviceGroupCount unsafe.Pointer, pPhysicalDeviceGroupProperties unsafe.Pointer) VkResult
	VkEnumeratePhysicalDeviceQueueFamilyPerformanceQueryCountersKHR func(physicalDevice VkPhysicalDevice, queueFamilyIndex uint32, pCounterCount unsafe.Pointer, pCounters unsafe.Pointer, pCounterDescriptions unsafe.Pointer) VkResult
	VkEnumeratePhysicalDevices                                      func(instance VkInstance, pPhysicalDeviceCount unsafe.Pointer, pPhysicalDevices unsafe.Pointer) VkResult
	VkFlushMappedMemoryRanges                                       func(device VkDevice, memoryRangeCount uint32, pMemoryRanges unsafe.Pointer) VkResult
	VkFreeCommandBuffers                                            func(device VkDevice, commandPool VkCommandPool, commandBufferCount uint32, pCommandBuffers unsafe.Pointer)
	VkFreeDescriptorSets                                            func(device VkDevice, descriptorPool VkDescriptorPool, descriptorSetCount uint32, pDescriptorSets unsafe.Pointer) VkResult
	VkFreeMemory                                                    func(device VkDevice, memory VkDeviceMemory, pAllocator unsafe.Pointer)
	VkGetAccelerationStructureBuildSizesKHR                         func(device VkDevice, buildType VkAccelerationStructureBuildTypeKHR, pBuildInfo unsafe.Pointer, pMaxPrimitiveCounts unsafe.Pointer, pSizeInfo unsafe.Pointer)
	VkGetAccelerationStructureDeviceAddressKHR                      func(device VkDevice, pInfo unsafe.Pointer) VkDeviceAddress
	VkGetAccelerationStructureOpaqueCaptureDescriptorDataEXT        func(device VkDevice, pInfo unsafe.Pointer, pData unsafe.Pointer) VkResult
	VkGetBufferDeviceAddress                                        func(device VkDevice, pInfo unsafe.Pointer) VkDeviceAddress
	VkGetBufferMemoryRequirements                                   func(device VkDevice, buffer VkBuffer, pMemoryRequirements unsafe.Pointer)
	VkGetBufferMemoryRequirements2                                  func(device VkDevice, pInfo unsafe.Pointer, pMemoryRequirements unsafe.Pointer)
	VkGetBufferOpaqueCaptureAddress                                 func(device VkDevice, pInfo unsafe.Pointer) uint64
	VkGetBufferOpaqueCaptureDescriptorDataEXT                       func(device VkDevice, pInfo unsafe.Pointer, pData unsafe.Pointer) VkResult
	VkGetCalibratedTimestampsKHR                                    func(device VkDevice, timestampCount uint32, pTimestampInfos unsafe.Pointer, pTimestamps unsafe.Pointer, pMaxDeviation unsafe.Pointer) VkResult
	VkGetDeferredOperationMaxConcurrencyKHR                         func(device VkDevice, operation VkDeferredOperationKHR) uint32
	VkGetDeferredOperationResultKHR                                 func(device VkDevice, operation VkDeferredOperationKHR) VkResult
	VkGetDescriptorEXT                                              func(device VkDevice, pDescriptorInfo unsafe.Pointer, dataSize uintptr, pDescriptor unsafe.Pointer)
	VkGetDescriptorSetLayoutBindingOffsetEXT                        func(device VkDevice, layout VkDescriptorSetLayout, binding uint32, pOffset unsafe.Pointer)
	VkGetDescriptorSetLayoutSizeEXT                                 func(device VkDevice, layout VkDescriptorSetLayout, pLayoutSizeInBytes unsafe.Pointer)
	VkGetDescriptorSetLayoutSupport                                 func(device VkDevice, pCreateInfo unsafe.Pointer, pSupport unsafe.Pointer)
	VkGetDeviceAccelerationStructureCompatibilityKHR                func(device VkDevice, pVersionInfo unsafe.Pointer, pCompatibility unsafe.Pointer)
	VkGetDeviceBufferMemoryRequirements                             func(device VkDevice, pInfo unsafe.Pointer, pMemoryRequirements unsafe.Pointer)
	VkGetDeviceFaultDebugInfoKHR                                    func(device VkDevice, pDebugInfo unsafe.Pointer) VkResult
	VkGetDeviceFaultInfoEXT                                         func(device VkDevice, pFaultCounts unsafe.Pointer, pFaultInfo unsafe.Pointer) VkResult
	VkGetDeviceFaultReportsKHR                                      func(device VkDevice, timeout uint64, pFaultCounts unsafe.Pointer, pFaultInfo unsafe.Pointer) VkResult
	VkGetDeviceGroupPeerMemoryFeatures                              func(device VkDevice, heapIndex uint32, localDeviceIndex uint32, remoteDeviceIndex uint32, pPeerMemoryFeatures unsafe.Pointer)
	VkGetDeviceGroupPresentCapabilitiesKHR                          func(device VkDevice, pDeviceGroupPresentCapabilities unsafe.Pointer) VkResult
	VkGetDeviceGroupSurfacePresentModesKHR                          func(device VkDevice, surface VkSurfaceKHR, pModes unsafe.Pointer) VkResult
	VkGetDeviceImageMemoryRequirements                              func(device VkDevice, pInfo unsafe.Pointer, pMemoryRequirements unsafe.Pointer)
	VkGetDeviceImageSparseMemoryRequirements                        func(device VkDevice, pInfo unsafe.Pointer, pSparseMemoryRequirementCount unsafe.Pointer, pSparseMemoryRequirements unsafe.Pointer)
	VkGetDeviceImageSubresourceLayout                               func(device VkDevice, pInfo unsafe.Pointer, pLayout unsafe.Pointer)
	VkGetDeviceMemoryCommitment                                     func(device VkDevice, memory VkDeviceMemory, pCommittedMemoryInBytes unsafe.Pointer)
	VkGetDeviceMemoryOpaqueCaptureAddress                           func(device VkDevice, pInfo unsafe.Pointer) uint64
	VkGetDeviceMicromapCompatibilityEXT                             func(device VkDevice, pVersionInfo unsafe.Pointer, pCompatibility unsafe.Pointer)
	VkGetDeviceQueue                                                func(device VkDevice, queueFamilyIndex uint32, queueIndex uint32, pQueue unsafe.Pointer)
	VkGetDeviceQueue2                                               func(device VkDevice, pQueueInfo unsafe.Pointer, pQueue unsafe.Pointer)
	VkGetDisplayModeProperties2KHR                                  func(physicalDevice VkPhysicalDevice, display VkDisplayKHR, pPropertyCount unsafe.Pointer, pProperties unsafe.Pointer) VkResult
	VkGetDisplayModePropertiesKHR                                   func(physicalDevice VkPhysicalDevice, display VkDisplayKHR, pPropertyCount unsafe.Pointer, pProperties unsafe.Pointer) VkResult
	VkGetDisplayPlaneCapabilities2KHR                               func(physicalDevice VkPhysicalDevice, pDisplayPlaneInfo unsafe.Pointer, pCapabilities unsafe.Pointer) VkResult
	VkGetDisplayPlaneCapabilitiesKHR                                func(physicalDevice VkPhysicalDevice, mode VkDisplayModeKHR, planeIndex uint32, pCapabilities unsafe.Pointer) VkResult
	VkGetDisplayPlaneSupportedDisplaysKHR                           func(physicalDevice VkPhysicalDevice, planeIndex uint32, pDisplayCount unsafe.Pointer, pDisplays unsafe.Pointer) VkResult
	VkGetDrmDisplayEXT                                              func(physicalDevice VkPhysicalDevice, drmFd int32, connectorId uint32, display unsafe.Pointer) VkResult
	VkGetEncodedVideoSessionParametersKHR                           func(device VkDevice, pVideoSessionParametersInfo unsafe.Pointer, pFeedbackInfo unsafe.Pointer, pDataSize unsafe.Pointer, pData unsafe.Pointer) VkResult
	VkGetEventStatus                                                func(device VkDevice, event VkEvent) VkResult
	VkGetFenceFdKHR                                                 func(device VkDevice, pGetFdInfo unsafe.Pointer, pFd unsafe.Pointer) VkResult
	VkGetFenceStatus                                                func(device VkDevice, fence VkFence) VkResult
	VkGetGeneratedCommandsMemoryRequirementsEXT                     func(device VkDevice, pInfo unsafe.Pointer, pMemoryRequirements unsafe.Pointer)
	VkGetImageDrmFormatModifierPropertiesEXT                        func(device VkDevice, image VkImage, pProperties unsafe.Pointer) VkResult
	VkGetImageMemoryRequirements                                    func(device VkDevice, image VkImage, pMemoryRequirements unsafe.Pointer)
	VkGetImageMemoryRequirements2                                   func(device VkDevice, pInfo unsafe.Pointer, pMemoryRequirements unsafe.Pointer)
	VkGetImageOpaqueCaptureDataEXT                                  func(device VkDevice, imageCount uint32, pImages unsafe.Pointer, pDatas unsafe.Pointer) VkResult
	VkGetImageOpaqueCaptureDescriptorDataEXT                        func(device VkDevice, pInfo unsafe.Pointer, pData unsafe.Pointer) VkResult
	VkGetImageSparseMemoryRequirements                              func(device VkDevice, image VkImage, pSparseMemoryRequirementCount unsafe.Pointer, pSparseMemoryRequirements unsafe.Pointer)
	VkGetImageSparseMemoryRequirements2                             func(device VkDevice, pInfo unsafe.Pointer, pSparseMemoryRequirementCount unsafe.Pointer, pSparseMemoryRequirements unsafe.Pointer)
	VkGetImageSubresourceLayout                                     func(device VkDevice, image VkImage, pSubresource unsafe.Pointer, pLayout unsafe.Pointer)
	VkGetImageSubresourceLayout2                                    func(device VkDevice, image VkImage, pSubresource unsafe.Pointer, pLayout unsafe.Pointer)
	VkGetImageViewOpaqueCaptureDescriptorDataEXT                    func(device VkDevice, pInfo unsafe.Pointer, pData unsafe.Pointer) VkResult
	VkGetMemoryFdKHR                                                func(device VkDevice, pGetFdInfo unsafe.Pointer, pFd unsafe.Pointer) VkResult
	VkGetMemoryFdPropertiesKHR                                      func(device VkDevice, handleType VkExternalMemoryHandleTypeFlagBits, fd int32, pMemoryFdProperties unsafe.Pointer) VkResult
	VkGetMemoryHostPointerPropertiesEXT                             func(device VkDevice, handleType VkExternalMemoryHandleTypeFlagBits, pHostPointer unsafe.Pointer, pMemoryHostPointerProperties unsafe.Pointer) VkResult
	VkGetMicromapBuildSizesEXT                                      func(device VkDevice, buildType VkAccelerationStructureBuildTypeKHR, pBuildInfo unsafe.Pointer, pSizeInfo unsafe.Pointer)
	VkGetPastPresentationTimingEXT                                  func(device VkDevice, pPastPresentationTimingInfo unsafe.Pointer, pPastPresentationTimingProperties unsafe.Pointer) VkResult
	VkGetPhysicalDeviceCalibrateableTimeDomainsKHR                  func(physicalDevice VkPhysicalDevice, pTimeDomainCount unsafe.Pointer, pTimeDomains unsafe.Pointer) VkResult
	VkGetPhysicalDeviceCooperativeMatrixPropertiesKHR               func(physicalDevice VkPhysicalDevice, pPropertyCount unsafe.Pointer, pProperties unsafe.Pointer) VkResult
	VkGetPhysicalDeviceDescriptorSizeEXT                            func(physicalDevice VkPhysicalDevice, descriptorType VkDescriptorType) VkDeviceSize
	VkGetPhysicalDeviceDisplayPlaneProperties2KHR                   func(physicalDevice VkPhysicalDevice, pPropertyCount unsafe.Pointer, pProperties unsafe.Pointer) VkResult
	VkGetPhysicalDeviceDisplayPlanePropertiesKHR                    func(physicalDevice VkPhysicalDevice, pPropertyCount unsafe.Pointer, pProperties unsafe.Pointer) VkResult
	VkGetPhysicalDeviceDisplayProperties2KHR                        func(physicalDevice VkPhysicalDevice, pPropertyCount unsafe.Pointer, pProperties unsafe.Pointer) VkResult
	VkGetPhysicalDeviceDisplayPropertiesKHR                         func(physicalDevice VkPhysicalDevice, pPropertyCount unsafe.Pointer, pProperties unsafe.Pointer) VkResult
	VkGetPhysicalDeviceExternalBufferProperties                     func(physicalDevice VkPhysicalDevice, pExternalBufferInfo unsafe.Pointer, pExternalBufferProperties unsafe.Pointer)
	VkGetPhysicalDeviceExternalFenceProperties                      func(physicalDevice VkPhysicalDevice, pExternalFenceInfo unsafe.Pointer, pExternalFenceProperties unsafe.Pointer)
	VkGetPhysicalDeviceExternalSemaphoreProperties                  func(physicalDevice VkPhysicalDevice, pExternalSemaphoreInfo unsafe.Pointer, pExternalSemaphoreProperties unsafe.Pointer)
	VkGetPhysicalDeviceFeatures                                     func(physicalDevice VkPhysicalDevice, pFeatures unsafe.Pointer)
	VkGetPhysicalDeviceFeatures2                                    func(physicalDevice VkPhysicalDevice, pFeatures unsafe.Pointer)
	VkGetPhysicalDeviceFormatProperties                             func(physicalDevice VkPhysicalDevice, format VkFormat, pFormatProperties unsafe.Pointer)
	VkGetPhysicalDeviceFormatProperties2                            func(physicalDevice VkPhysicalDevice, format VkFormat, pFormatProperties unsafe.Pointer)
	VkGetPhysicalDeviceFragmentShadingRatesKHR                      func(physicalDevice VkPhysicalDevice, pFragmentShadingRateCount unsafe.Pointer, pFragmentShadingRates unsafe.Pointer) VkResult
	VkGetPhysicalDeviceImageFormatProperties                        func(physicalDevice VkPhysicalDevice, format VkFormat, type_ VkImageType, tiling VkImageTiling, usage VkImageUsageFlags, flags VkImageCreateFlags, pImageFormatProperties unsafe.Pointer) VkResult
	VkGetPhysicalDeviceImageFormatProperties2                       func(physicalDevice VkPhysicalDevice, pImageFormatInfo unsafe.Pointer, pImageFormatProperties unsafe.Pointer) VkResult
	VkGetPhysicalDeviceMemoryProperties                             func(physicalDevice VkPhysicalDevice, pMemoryProperties unsafe.Pointer)
	VkGetPhysicalDeviceMemoryProperties2                            func(physicalDevice VkPhysicalDevice, pMemoryProperties unsafe.Pointer)
	VkGetPhysicalDeviceMultisamplePropertiesEXT                     func(physicalDevice VkPhysicalDevice, samples VkSampleCountFlagBits, pMultisampleProperties unsafe.Pointer)
	VkGetPhysicalDevicePresentRectanglesKHR                         func(physicalDevice VkPhysicalDevice, surface VkSurfaceKHR, pRectCount unsafe.Pointer, pRects unsafe.Pointer) VkResult
	VkGetPhysicalDeviceProperties                                   func(physicalDevice VkPhysicalDevice, pProperties unsafe.Pointer)
	VkGetPhysicalDeviceProperties2                                  func(physicalDevice VkPhysicalDevice, pProperties unsafe.Pointer)
	VkGetPhysicalDeviceQueueFamilyPerformanceQueryPassesKHR         func(physicalDevice VkPhysicalDevice, pPerformanceQueryCreateInfo unsafe.Pointer, pNumPasses unsafe.Pointer)
	VkGetPhysicalDeviceQueueFamilyProperties                        func(physicalDevice VkPhysicalDevice, pQueueFamilyPropertyCount unsafe.Pointer, pQueueFamilyProperties unsafe.Pointer)
	VkGetPhysicalDeviceQueueFamilyProperties2                       func(physicalDevice VkPhysicalDevice, pQueueFamilyPropertyCount unsafe.Pointer, pQueueFamilyProperties unsafe.Pointer)
	VkGetPhysicalDeviceSparseImageFormatProperties                  func(physicalDevice VkPhysicalDevice, format VkFormat, type_ VkImageType, samples VkSampleCountFlagBits, usage VkImageUsageFlags, tiling VkImageTiling, pPropertyCount unsafe.Pointer, pProperties unsafe.Pointer)
	VkGetPhysicalDeviceSparseImageFormatProperties2                 func(physicalDevice VkPhysicalDevice, pFormatInfo unsafe.Pointer, pPropertyCount unsafe.Pointer, pProperties unsafe.Pointer)
	VkGetPhysicalDeviceSurfaceCapabilities2EXT                      func(physicalDevice VkPhysicalDevice, surface VkSurfaceKHR, pSurfaceCapabilities unsafe.Pointer) VkResult
	VkGetPhysicalDeviceSurfaceCapabilities2KHR                      func(physicalDevice VkPhysicalDevice, pSurfaceInfo unsafe.Pointer, pSurfaceCapabilities unsafe.Pointer) VkResult
	VkGetPhysicalDeviceSurfaceCapabilitiesKHR                       func(physicalDevice VkPhysicalDevice, surface VkSurfaceKHR, pSurfaceCapabilities unsafe.Pointer) VkResult
	VkGetPhysicalDeviceSurfaceFormats2KHR                           func(physicalDevice VkPhysicalDevice, pSurfaceInfo unsafe.Pointer, pSurfaceFormatCount unsafe.Pointer, pSurfaceFormats unsafe.Pointer) VkResult
	VkGetPhysicalDeviceSurfaceFormatsKHR                            func(physicalDevice VkPhysicalDevice, surface VkSurfaceKHR, pSurfaceFormatCount unsafe.Pointer, pSurfaceFormats unsafe.Pointer) VkResult
	VkGetPhysicalDeviceSurfacePresentModesKHR                       func(physicalDevice VkPhysicalDevice, surface VkSurfaceKHR, pPresentModeCount unsafe.Pointer, pPresentModes unsafe.Pointer) VkResult
	VkGetPhysicalDeviceSurfaceSupportKHR                            func(physicalDevice VkPhysicalDevice, queueFamilyIndex uint32, surface VkSurfaceKHR, pSupported unsafe.Pointer) VkResult
	VkGetPhysicalDeviceToolProperties                               func(physicalDevice VkPhysicalDevice, pToolCount unsafe.Pointer, pToolProperties unsafe.Pointer) VkResult
	VkGetPhysicalDeviceVideoCapabilitiesKHR                         func(physicalDevice VkPhysicalDevice, pVideoProfile unsafe.Pointer, pCapabilities unsafe.Pointer) VkResult
	VkGetPhysicalDeviceVideoEncodeQualityLevelPropertiesKHR         func(physicalDevice VkPhysicalDevice, pQualityLevelInfo unsafe.Pointer, pQualityLevelProperties unsafe.Pointer) VkResult
	VkGetPhysicalDeviceVideoFormatPropertiesKHR                     func(physicalDevice VkPhysicalDevice, pVideoFormatInfo unsafe.Pointer, pVideoFormatPropertyCount unsafe.Pointer, pVideoFormatProperties unsafe.Pointer) VkResult
	VkGetPipelineBinaryDataKHR                                      func(device VkDevice, pInfo unsafe.Pointer, pPipelineBinaryKey unsafe.Pointer, pPipelineBinaryDataSize unsafe.Pointer, pPipelineBinaryData unsafe.Pointer) VkResult
	VkGetPipelineCacheData                                          func(device VkDevice, pipelineCache VkPipelineCache, pDataSize unsafe.Pointer, pData unsafe.Pointer) VkResult
	VkGetPipelineExecutableInternalRepresentationsKHR               func(device VkDevice, pExecutableInfo unsafe.Pointer, pInternalRepresentationCount unsafe.Pointer, pInternalRepresentations unsafe.Pointer) VkResult
	VkGetPipelineExecutablePropertiesKHR                            func(device VkDevice, pPipelineInfo unsafe.Pointer, pExecutableCount unsafe.Pointer, pProperties unsafe.Pointer) VkResult
	VkGetPipelineExecutableStatisticsKHR                            func(device VkDevice, pExecutableInfo unsafe.Pointer, pStatisticCount unsafe.Pointer, pStatistics unsafe.Pointer) VkResult
	VkGetPipelineKeyKHR                                             func(device VkDevice, pPipelineCreateInfo unsafe.Pointer, pPipelineKey unsafe.Pointer) VkResult
	VkGetPipelinePropertiesEXT                                      func(device VkDevice, pPipelineInfo unsafe.Pointer, pPipelineProperties unsafe.Pointer) VkResult
	VkGetPrivateData                                                func(device VkDevice, objectType VkObjectType, objectHandle uint64, privateDataSlot VkPrivateDataSlot, pData unsafe.Pointer)
	VkGetQueryPoolResults                                           func(device VkDevice, queryPool VkQueryPool, firstQuery uint32, queryCount uint32, dataSize uintptr, pData unsafe.Pointer, stride VkDeviceSize, flags VkQueryResultFlags) VkResult
	VkGetRayTracingCaptureReplayShaderGroupHandlesKHR               func(device VkDevice, pipeline VkPipeline, firstGroup uint32, groupCount uint32, dataSize uintptr, pData unsafe.Pointer) VkResult
	VkGetRayTracingShaderGroupHandlesKHR                            func(device VkDevice, pipeline VkPipeline, firstGroup uint32, groupCount uint32, dataSize uintptr, pData unsafe.Pointer) VkResult
	VkGetRayTracingShaderGroupStackSizeKHR                          func(device VkDevice, pipeline VkPipeline, group uint32, groupShader VkShaderGroupShaderKHR) VkDeviceSize
	VkGetRenderAreaGranularity                                      func(device VkDevice, renderPass VkRenderPass, pGranularity unsafe.Pointer)
	VkGetRenderingAreaGranularity                                   func(device VkDevice, pRenderingAreaInfo unsafe.Pointer, pGranularity unsafe.Pointer)
	VkGetSamplerOpaqueCaptureDescriptorDataEXT                      func(device VkDevice, pInfo unsafe.Pointer, pData unsafe.Pointer) VkResult
	VkGetSemaphoreCounterValue                                      func(device VkDevice, semaphore VkSemaphore, pValue unsafe.Pointer) VkResult
	VkGetSemaphoreFdKHR                                             func(device VkDevice, pGetFdInfo unsafe.Pointer, pFd unsafe.Pointer) VkResult
	VkGetShaderBinaryDataEXT                                        func(device VkDevice, shader VkShaderEXT, pDataSize unsafe.Pointer, pData unsafe.Pointer) VkResult
	VkGetShaderModuleCreateInfoIdentifierEXT                        func(device VkDevice, pCreateInfo unsafe.Pointer, pIdentifier unsafe.Pointer)
	VkGetShaderModuleIdentifierEXT                                  func(device VkDevice, shaderModule VkShaderModule, pIdentifier unsafe.Pointer)
	VkGetSwapchainCounterEXT                                        func(device VkDevice, swapchain VkSwapchainKHR, counter VkSurfaceCounterFlagBitsEXT, pCounterValue unsafe.Pointer) VkResult
	VkGetSwapchainImagesKHR                                         func(device VkDevice, swapchain VkSwapchainKHR, pSwapchainImageCount unsafe.Pointer, pSwapchainImages unsafe.Pointer) VkResult
	VkGetSwapchainStatusKHR                                         func(device VkDevice, swapchain VkSwapchainKHR) VkResult
	VkGetSwapchainTimeDomainPropertiesEXT                           func(device VkDevice, swapchain VkSwapchainKHR, pSwapchainTimeDomainProperties unsafe.Pointer, pTimeDomainsCounter unsafe.Pointer) VkResult
	VkGetSwapchainTimingPropertiesEXT                               func(device VkDevice, swapchain VkSwapchainKHR, pSwapchainTimingProperties unsafe.Pointer, pSwapchainTimingPropertiesCounter unsafe.Pointer) VkResult
	VkGetTensorOpaqueCaptureDataARM                                 func(device VkDevice, tensorCount uint32, pTensors unsafe.Pointer, pDatas unsafe.Pointer) VkResult
	VkGetValidationCacheDataEXT                                     func(device VkDevice, validationCache VkValidationCacheEXT, pDataSize unsafe.Pointer, pData unsafe.Pointer) VkResult
	VkGetVideoSessionMemoryRequirementsKHR                          func(device VkDevice, videoSession VkVideoSessionKHR, pMemoryRequirementsCount unsafe.Pointer, pMemoryRequirements unsafe.Pointer) VkResult
	VkImportFenceFdKHR                                              func(device VkDevice, pImportFenceFdInfo unsafe.Pointer) VkResult
	VkImportSemaphoreFdKHR                                          func(device VkDevice, pImportSemaphoreFdInfo unsafe.Pointer) VkResult
	VkInvalidateMappedMemoryRanges                                  func(device VkDevice, memoryRangeCount uint32, pMemoryRanges unsafe.Pointer) VkResult
	VkMapMemory                                                     func(device VkDevice, memory VkDeviceMemory, offset VkDeviceSize, size VkDeviceSize, flags VkMemoryMapFlags, ppData unsafe.Pointer) VkResult
	VkMapMemory2                                                    func(device VkDevice, pMemoryMapInfo unsafe.Pointer, ppData unsafe.Pointer) VkResult
	VkMergePipelineCaches                                           func(device VkDevice, dstCache VkPipelineCache, srcCacheCount uint32, pSrcCaches unsafe.Pointer) VkResult
	VkMergeValidationCachesEXT                                      func(device VkDevice, dstCache VkValidationCacheEXT, srcCacheCount uint32, pSrcCaches unsafe.Pointer) VkResult
	VkQueueBeginDebugUtilsLabelEXT                                  func(queue VkQueue, pLabelInfo unsafe.Pointer)
	VkQueueBindSparse                                               func(queue VkQueue, bindInfoCount uint32, pBindInfo unsafe.Pointer, fence VkFence) VkResult
	VkQueueEndDebugUtilsLabelEXT                                    func(queue VkQueue)
	VkQueueInsertDebugUtilsLabelEXT                                 func(queue VkQueue, pLabelInfo unsafe.Pointer)
	VkQueuePresentKHR                                               func(queue VkQueue, pPresentInfo unsafe.Pointer) VkResult
	VkQueueSubmit                                                   func(queue VkQueue, submitCount uint32, pSubmits unsafe.Pointer, fence VkFence) VkResult
	VkQueueSubmit2                                                  func(queue VkQueue, submitCount uint32, pSubmits unsafe.Pointer, fence VkFence) VkResult
	VkQueueWaitIdle                                                 func(queue VkQueue) VkResult
	VkRegisterCustomBorderColorEXT                                  func(device VkDevice, pBorderColor unsafe.Pointer, requestIndex VkBool32, pIndex unsafe.Pointer) VkResult
	VkRegisterDeviceEventEXT                                        func(device VkDevice, pDeviceEventInfo unsafe.Pointer, pAllocator unsafe.Pointer, pFence unsafe.Pointer) VkResult
	VkRegisterDisplayEventEXT                                       func(device VkDevice, display VkDisplayKHR, pDisplayEventInfo unsafe.Pointer, pAllocator unsafe.Pointer, pFence unsafe.Pointer) VkResult
	VkReleaseCapturedPipelineDataKHR                                func(device VkDevice, pInfo unsafe.Pointer, pAllocator unsafe.Pointer) VkResult
	VkReleaseDisplayEXT                                             func(physicalDevice VkPhysicalDevice, display VkDisplayKHR) VkResult
	VkReleaseProfilingLockKHR                                       func(device VkDevice)
	VkReleaseSwapchainImagesKHR                                     func(device VkDevice, pReleaseInfo unsafe.Pointer) VkResult
	VkResetCommandBuffer                                            func(commandBuffer VkCommandBuffer, flags VkCommandBufferResetFlags) VkResult
	VkResetCommandPool                                              func(device VkDevice, commandPool VkCommandPool, flags VkCommandPoolResetFlags) VkResult
	VkResetDescriptorPool                                           func(device VkDevice, descriptorPool VkDescriptorPool, flags VkDescriptorPoolResetFlags) VkResult
	VkResetEvent                                                    func(device VkDevice, event VkEvent) VkResult
	VkResetFences                                                   func(device VkDevice, fenceCount uint32, pFences unsafe.Pointer) VkResult
	VkResetQueryPool                                                func(device VkDevice, queryPool VkQueryPool, firstQuery uint32, queryCount uint32)
	VkSetDebugUtilsObjectNameEXT                                    func(device VkDevice, pNameInfo unsafe.Pointer) VkResult
	VkSetDebugUtilsObjectTagEXT                                     func(device VkDevice, pTagInfo unsafe.Pointer) VkResult
	VkSetDeviceMemoryPriorityEXT                                    func(device VkDevice, memory VkDeviceMemory, priority float32)
	VkSetEvent                                                      func(device VkDevice, event VkEvent) VkResult
	VkSetHdrMetadataEXT                                             func(device VkDevice, swapchainCount uint32, pSwapchains unsafe.Pointer, pMetadata unsafe.Pointer)
	VkSetPrivateData                                                func(device VkDevice, objectType VkObjectType, objectHandle uint64, privateDataSlot VkPrivateDataSlot, data uint64) VkResult
	VkSetSwapchainPresentTimingQueueSizeEXT                         func(device VkDevice, swapchain VkSwapchainKHR, size uint32) VkResult
	VkSignalSemaphore                                               func(device VkDevice, pSignalInfo unsafe.Pointer) VkResult
	VkSubmitDebugUtilsMessageEXT                                    func(instance VkInstance, messageSeverity VkDebugUtilsMessageSeverityFlagBitsEXT, messageTypes VkDebugUtilsMessageTypeFlagsEXT, pCallbackData unsafe.Pointer)
	VkTransitionImageLayout                                         func(device VkDevice, transitionCount uint32, pTransitions unsafe.Pointer) VkResult
	VkTrimCommandPool                                               func(device VkDevice, commandPool VkCommandPool, flags VkCommandPoolTrimFlags)
	VkUnmapMemory                                                   func(device VkDevice, memory VkDeviceMemory)
	VkUnmapMemory2                                                  func(device VkDevice, pMemoryUnmapInfo unsafe.Pointer) VkResult
	VkUnregisterCustomBorderColorEXT                                func(device VkDevice, index uint32)
	VkUpdateDescriptorSetWithTemplate                               func(device VkDevice, descriptorSet VkDescriptorSet, descriptorUpdateTemplate VkDescriptorUpdateTemplate, pData unsafe.Pointer)
	VkUpdateDescriptorSets                                          func(device VkDevice, descriptorWriteCount uint32, pDescriptorWrites unsafe.Pointer, descriptorCopyCount uint32, pDescriptorCopies unsafe.Pointer)
	VkUpdateIndirectExecutionSetPipelineEXT                         func(device VkDevice, indirectExecutionSet VkIndirectExecutionSetEXT, executionSetWriteCount uint32, pExecutionSetWrites unsafe.Pointer)
	VkUpdateIndirectExecutionSetShaderEXT                           func(device VkDevice, indirectExecutionSet VkIndirectExecutionSetEXT, executionSetWriteCount uint32, pExecutionSetWrites unsafe.Pointer)
	VkUpdateVideoSessionParametersKHR                               func(device VkDevice, videoSessionParameters VkVideoSessionParametersKHR, pUpdateInfo unsafe.Pointer) VkResult
	VkWaitForFences                                                 func(device VkDevice, fenceCount uint32, pFences unsafe.Pointer, waitAll VkBool32, timeout uint64) VkResult
	VkWaitForPresent2KHR                                            func(device VkDevice, swapchain VkSwapchainKHR, pPresentWait2Info unsafe.Pointer) VkResult
	VkWaitForPresentKHR                                             func(device VkDevice, swapchain VkSwapchainKHR, presentId uint64, timeout uint64) VkResult
	VkWaitSemaphores                                                func(device VkDevice, pWaitInfo unsafe.Pointer, timeout uint64) VkResult
	VkWriteAccelerationStructuresPropertiesKHR                      func(device VkDevice, accelerationStructureCount uint32, pAccelerationStructures unsafe.Pointer, queryType VkQueryType, dataSize uintptr, pData unsafe.Pointer, stride uintptr) VkResult
	VkWriteMicromapsPropertiesEXT                                   func(device VkDevice, micromapCount uint32, pMicromaps unsafe.Pointer, queryType VkQueryType, dataSize uintptr, pData unsafe.Pointer, stride uintptr) VkResult
	VkWriteResourceDescriptorsEXT                                   func(device VkDevice, resourceCount uint32, pResources unsafe.Pointer, pDescriptors unsafe.Pointer) VkResult
	VkWriteSamplerDescriptorsEXT                                    func(device VkDevice, samplerCount uint32, pSamplers unsafe.Pointer, pDescriptors unsafe.Pointer) VkResult
)

var _ = unsafe.Pointer(nil)
