// Code generated by vkgen; DO NOT EDIT.

package vulkan

// API constants from the registry (VK_MAX_*, VK_UUID_SIZE, etc.).
const (
	VK_COMPRESSED_TRIANGLE_FORMAT_DGF1_BYTE_ALIGNMENT_AMDX        = 128
	VK_COMPRESSED_TRIANGLE_FORMAT_DGF1_BYTE_STRIDE_AMDX           = 128
	VK_COMPUTE_OCCUPANCY_PRIORITY_HIGH_NV                         = 0.75
	VK_COMPUTE_OCCUPANCY_PRIORITY_LOW_NV                          = 0.25
	VK_COMPUTE_OCCUPANCY_PRIORITY_NORMAL_NV                       = 0.50
	VK_DATA_GRAPH_MODEL_TOOLCHAIN_VERSION_LENGTH_QCOM             = 3
	VK_FALSE                                                      = 0
	VK_LOD_CLAMP_NONE                                             = 1000.0
	VK_LUID_SIZE                                                  = 8
	VK_MAX_DATA_GRAPH_TOSA_NAME_SIZE_ARM                          = 128
	VK_MAX_DESCRIPTION_SIZE                                       = 256
	VK_MAX_DEVICE_GROUP_SIZE                                      = 32
	VK_MAX_DRIVER_INFO_SIZE                                       = 256
	VK_MAX_DRIVER_NAME_SIZE                                       = 256
	VK_MAX_EXTENSION_NAME_SIZE                                    = 256
	VK_MAX_GLOBAL_PRIORITY_SIZE                                   = 16
	VK_MAX_MEMORY_HEAPS                                           = 16
	VK_MAX_MEMORY_TYPES                                           = 32
	VK_MAX_PHYSICAL_DEVICE_DATA_GRAPH_OPERATION_SET_NAME_SIZE_ARM = 128
	VK_MAX_PHYSICAL_DEVICE_NAME_SIZE                              = 256
	VK_MAX_PIPELINE_BINARY_KEY_SIZE_KHR                           = 32
	VK_MAX_SHADER_MODULE_IDENTIFIER_SIZE_EXT                      = 32
	VK_MAX_VIDEO_AV1_REFERENCES_PER_FRAME_KHR                     = 7
	VK_MAX_VIDEO_VP9_REFERENCES_PER_FRAME_KHR                     = 3
	VK_TRUE                                                       = 1
	VK_UUID_SIZE                                                  = 16
)
