// Code generated by vkgen; DO NOT EDIT.

package vulkan

type PFN_vkAllocationFunction = uintptr
type PFN_vkDebugReportCallbackEXT = uintptr
type PFN_vkDebugUtilsMessengerCallbackEXT = uintptr
type PFN_vkDeviceMemoryReportCallbackEXT = uintptr
type PFN_vkFreeFunction = uintptr
type PFN_vkInternalAllocationNotification = uintptr
type PFN_vkInternalFreeNotification = uintptr
type PFN_vkReallocationFunction = uintptr
type PFN_vkVoidFunction = uintptr
