// Code generated by vkgen; DO NOT EDIT.

package vulkan

// Dispatchable handles are pointer-sized.
type (
	VkCommandBuffer  = uintptr
	VkDevice         = uintptr
	VkInstance       = uintptr
	VkPhysicalDevice = uintptr
	VkQueue          = uintptr
)

// Non-dispatchable handles are 64-bit on all platforms.
type (
	VkAccelerationStructureKHR  = uint64
	VkAccelerationStructureNV   = uint64
	VkBuffer                    = uint64
	VkBufferView                = uint64
	VkCommandPool               = uint64
	VkDebugReportCallbackEXT    = uint64
	VkDebugUtilsMessengerEXT    = uint64
	VkDeferredOperationKHR      = uint64
	VkDescriptorPool            = uint64
	VkDescriptorSet             = uint64
	VkDescriptorSetLayout       = uint64
	VkDescriptorUpdateTemplate  = uint64
	VkDeviceMemory              = uint64
	VkDisplayKHR                = uint64
	VkDisplayModeKHR            = uint64
	VkEvent                     = uint64
	VkFence                     = uint64
	VkFramebuffer               = uint64
	VkImage                     = uint64
	VkImageView                 = uint64
	VkIndirectCommandsLayoutEXT = uint64
	VkIndirectExecutionSetEXT   = uint64
	VkMicromapEXT               = uint64
	VkPipeline                  = uint64
	VkPipelineBinaryKHR         = uint64
	VkPipelineCache             = uint64
	VkPipelineLayout            = uint64
	VkPrivateDataSlot           = uint64
	VkQueryPool                 = uint64
	VkRenderPass                = uint64
	VkSampler                   = uint64
	VkSamplerYcbcrConversion    = uint64
	VkSemaphore                 = uint64
	VkShaderEXT                 = uint64
	VkShaderModule              = uint64
	VkSurfaceKHR                = uint64
	VkSwapchainKHR              = uint64
	VkTensorARM                 = uint64
	VkValidationCacheEXT        = uint64
	VkVideoSessionKHR           = uint64
	VkVideoSessionParametersKHR = uint64
)

type VkDescriptorUpdateTemplateKHR = VkDescriptorUpdateTemplate
type VkSamplerYcbcrConversionKHR = VkSamplerYcbcrConversion
type VkPrivateDataSlotEXT = VkPrivateDataSlot
