// Code generated by vkgen; DO NOT EDIT.

package vulkan

import "unsafe"

// VkClearColorValue is a C union stored as a byte array sized to its largest member.
type VkClearColorValue [16]byte

func (u *VkClearColorValue) AsFloat32() *[4]float32 { return (*[4]float32)(unsafe.Pointer(u)) }
func (u *VkClearColorValue) AsInt32() *[4]int32     { return (*[4]int32)(unsafe.Pointer(u)) }
func (u *VkClearColorValue) AsUint32() *[4]uint32   { return (*[4]uint32)(unsafe.Pointer(u)) }

// VkClearValue is a C union stored as a byte array sized to its largest member.
type VkClearValue [16]byte

func (u *VkClearValue) AsColor() *VkClearColorValue { return (*VkClearColorValue)(unsafe.Pointer(u)) }
func (u *VkClearValue) AsDepthStencil() *VkClearDepthStencilValue {
	return (*VkClearDepthStencilValue)(unsafe.Pointer(u))
}

// VkPerformanceCounterResultKHR is a C union stored as a byte array sized to its largest member.
type VkPerformanceCounterResultKHR [8]byte

func (u *VkPerformanceCounterResultKHR) AsInt32() *int32     { return (*int32)(unsafe.Pointer(u)) }
func (u *VkPerformanceCounterResultKHR) AsInt64() *int64     { return (*int64)(unsafe.Pointer(u)) }
func (u *VkPerformanceCounterResultKHR) AsUint32() *uint32   { return (*uint32)(unsafe.Pointer(u)) }
func (u *VkPerformanceCounterResultKHR) AsUint64() *uint64   { return (*uint64)(unsafe.Pointer(u)) }
func (u *VkPerformanceCounterResultKHR) AsFloat32() *float32 { return (*float32)(unsafe.Pointer(u)) }
func (u *VkPerformanceCounterResultKHR) AsFloat64() *float64 { return (*float64)(unsafe.Pointer(u)) }

// VkPipelineExecutableStatisticValueKHR is a C union stored as a byte array sized to its largest member.
type VkPipelineExecutableStatisticValueKHR [8]byte

func (u *VkPipelineExecutableStatisticValueKHR) AsB32() *VkBool32 {
	return (*VkBool32)(unsafe.Pointer(u))
}
func (u *VkPipelineExecutableStatisticValueKHR) AsI64() *int64  { return (*int64)(unsafe.Pointer(u)) }
func (u *VkPipelineExecutableStatisticValueKHR) AsU64() *uint64 { return (*uint64)(unsafe.Pointer(u)) }
func (u *VkPipelineExecutableStatisticValueKHR) AsF64() *float64 {
	return (*float64)(unsafe.Pointer(u))
}

// VkDeviceOrHostAddressKHR is a C union stored as a byte array sized to its largest member.
type VkDeviceOrHostAddressKHR [8]byte

func (u *VkDeviceOrHostAddressKHR) AsDeviceAddress() *VkDeviceAddress {
	return (*VkDeviceAddress)(unsafe.Pointer(u))
}
func (u *VkDeviceOrHostAddressKHR) AsHostAddress() *unsafe.Pointer {
	return (*unsafe.Pointer)(unsafe.Pointer(u))
}

// VkDeviceOrHostAddressConstKHR is a C union stored as a byte array sized to its largest member.
type VkDeviceOrHostAddressConstKHR [8]byte

func (u *VkDeviceOrHostAddressConstKHR) AsDeviceAddress() *VkDeviceAddress {
	return (*VkDeviceAddress)(unsafe.Pointer(u))
}
func (u *VkDeviceOrHostAddressConstKHR) AsHostAddress() *unsafe.Pointer {
	return (*unsafe.Pointer)(unsafe.Pointer(u))
}

// VkAccelerationStructureGeometryDataKHR is a C union stored as a byte array sized to its largest member.
type VkAccelerationStructureGeometryDataKHR [56]byte

func (u *VkAccelerationStructureGeometryDataKHR) AsTriangles() *VkAccelerationStructureGeometryTrianglesDataKHR {
	return (*VkAccelerationStructureGeometryTrianglesDataKHR)(unsafe.Pointer(u))
}
func (u *VkAccelerationStructureGeometryDataKHR) AsAabbs() *VkAccelerationStructureGeometryAabbsDataKHR {
	return (*VkAccelerationStructureGeometryAabbsDataKHR)(unsafe.Pointer(u))
}
func (u *VkAccelerationStructureGeometryDataKHR) AsInstances() *VkAccelerationStructureGeometryInstancesDataKHR {
	return (*VkAccelerationStructureGeometryInstancesDataKHR)(unsafe.Pointer(u))
}

// VkIndirectExecutionSetInfoEXT is a C union stored as a byte array sized to its largest member.
type VkIndirectExecutionSetInfoEXT [8]byte

func (u *VkIndirectExecutionSetInfoEXT) AsPPipelineInfo() *unsafe.Pointer {
	return (*unsafe.Pointer)(unsafe.Pointer(u))
}
func (u *VkIndirectExecutionSetInfoEXT) AsPShaderInfo() *unsafe.Pointer {
	return (*unsafe.Pointer)(unsafe.Pointer(u))
}

// VkIndirectCommandsTokenDataEXT is a C union stored as a byte array sized to its largest member.
type VkIndirectCommandsTokenDataEXT [8]byte

func (u *VkIndirectCommandsTokenDataEXT) AsPPushConstant() *unsafe.Pointer {
	return (*unsafe.Pointer)(unsafe.Pointer(u))
}
func (u *VkIndirectCommandsTokenDataEXT) AsPVertexBuffer() *unsafe.Pointer {
	return (*unsafe.Pointer)(unsafe.Pointer(u))
}
func (u *VkIndirectCommandsTokenDataEXT) AsPIndexBuffer() *unsafe.Pointer {
	return (*unsafe.Pointer)(unsafe.Pointer(u))
}
func (u *VkIndirectCommandsTokenDataEXT) AsPExecutionSet() *unsafe.Pointer {
	return (*unsafe.Pointer)(unsafe.Pointer(u))
}

// VkDescriptorDataEXT is a C union stored as a byte array sized to its largest member.
type VkDescriptorDataEXT [8]byte

func (u *VkDescriptorDataEXT) AsPSampler() *unsafe.Pointer {
	return (*unsafe.Pointer)(unsafe.Pointer(u))
}
func (u *VkDescriptorDataEXT) AsPCombinedImageSampler() *unsafe.Pointer {
	return (*unsafe.Pointer)(unsafe.Pointer(u))
}
func (u *VkDescriptorDataEXT) AsPInputAttachmentImage() *unsafe.Pointer {
	return (*unsafe.Pointer)(unsafe.Pointer(u))
}
func (u *VkDescriptorDataEXT) AsPSampledImage() *unsafe.Pointer {
	return (*unsafe.Pointer)(unsafe.Pointer(u))
}
func (u *VkDescriptorDataEXT) AsPStorageImage() *unsafe.Pointer {
	return (*unsafe.Pointer)(unsafe.Pointer(u))
}
func (u *VkDescriptorDataEXT) AsPUniformTexelBuffer() *unsafe.Pointer {
	return (*unsafe.Pointer)(unsafe.Pointer(u))
}
func (u *VkDescriptorDataEXT) AsPStorageTexelBuffer() *unsafe.Pointer {
	return (*unsafe.Pointer)(unsafe.Pointer(u))
}
func (u *VkDescriptorDataEXT) AsPUniformBuffer() *unsafe.Pointer {
	return (*unsafe.Pointer)(unsafe.Pointer(u))
}
func (u *VkDescriptorDataEXT) AsPStorageBuffer() *unsafe.Pointer {
	return (*unsafe.Pointer)(unsafe.Pointer(u))
}
func (u *VkDescriptorDataEXT) AsAccelerationStructure() *VkDeviceAddress {
	return (*VkDeviceAddress)(unsafe.Pointer(u))
}

// VkResourceDescriptorDataEXT is a C union stored as a byte array sized to its largest member.
type VkResourceDescriptorDataEXT [8]byte

func (u *VkResourceDescriptorDataEXT) AsPImage() *unsafe.Pointer {
	return (*unsafe.Pointer)(unsafe.Pointer(u))
}
func (u *VkResourceDescriptorDataEXT) AsPTexelBuffer() *unsafe.Pointer {
	return (*unsafe.Pointer)(unsafe.Pointer(u))
}
func (u *VkResourceDescriptorDataEXT) AsPAddressRange() *unsafe.Pointer {
	return (*unsafe.Pointer)(unsafe.Pointer(u))
}
func (u *VkResourceDescriptorDataEXT) AsPTensorARM() *unsafe.Pointer {
	return (*unsafe.Pointer)(unsafe.Pointer(u))
}

// VkDescriptorMappingSourceDataEXT is a C union stored as a byte array sized to its largest member.
type VkDescriptorMappingSourceDataEXT [52]byte

func (u *VkDescriptorMappingSourceDataEXT) AsConstantOffset() *VkDescriptorMappingSourceConstantOffsetEXT {
	return (*VkDescriptorMappingSourceConstantOffsetEXT)(unsafe.Pointer(u))
}
func (u *VkDescriptorMappingSourceDataEXT) AsPushIndex() *VkDescriptorMappingSourcePushIndexEXT {
	return (*VkDescriptorMappingSourcePushIndexEXT)(unsafe.Pointer(u))
}
func (u *VkDescriptorMappingSourceDataEXT) AsIndirectIndex() *VkDescriptorMappingSourceIndirectIndexEXT {
	return (*VkDescriptorMappingSourceIndirectIndexEXT)(unsafe.Pointer(u))
}
func (u *VkDescriptorMappingSourceDataEXT) AsIndirectIndexArray() *VkDescriptorMappingSourceIndirectIndexArrayEXT {
	return (*VkDescriptorMappingSourceIndirectIndexArrayEXT)(unsafe.Pointer(u))
}
func (u *VkDescriptorMappingSourceDataEXT) AsHeapData() *VkDescriptorMappingSourceHeapDataEXT {
	return (*VkDescriptorMappingSourceHeapDataEXT)(unsafe.Pointer(u))
}
func (u *VkDescriptorMappingSourceDataEXT) AsPushDataOffset() *uint32 {
	return (*uint32)(unsafe.Pointer(u))
}
func (u *VkDescriptorMappingSourceDataEXT) AsPushAddressOffset() *uint32 {
	return (*uint32)(unsafe.Pointer(u))
}
func (u *VkDescriptorMappingSourceDataEXT) AsIndirectAddress() *VkDescriptorMappingSourceIndirectAddressEXT {
	return (*VkDescriptorMappingSourceIndirectAddressEXT)(unsafe.Pointer(u))
}
func (u *VkDescriptorMappingSourceDataEXT) AsShaderRecordIndex() *VkDescriptorMappingSourceShaderRecordIndexEXT {
	return (*VkDescriptorMappingSourceShaderRecordIndexEXT)(unsafe.Pointer(u))
}
func (u *VkDescriptorMappingSourceDataEXT) AsShaderRecordDataOffset() *uint32 {
	return (*uint32)(unsafe.Pointer(u))
}
func (u *VkDescriptorMappingSourceDataEXT) AsShaderRecordAddressOffset() *uint32 {
	return (*uint32)(unsafe.Pointer(u))
}

var _ = unsafe.Pointer(nil)
